Qiskit/qiskit-ibm-runtime

test/decorators.py, test/ibm/test_basic_server_paths.py, test/ibm/test_ibm_provider.py, test/ibm/test_jupyter.py
=> Fix broken push tests

test/utils.py
Noticed that every test run creates many empty files in my filesystem even though I do not set `FILE_LOG=True`.
=> Fix broken if conditions in setup_test_logging

qiskit_ibm_runtime/utils/json.py, releasenotes/notes/fix-qpy-v3-serialisation-20ddba46e7c6ba09.yaml
Terra 0.19.1 included a new version of the QPY format, which affects how
`ParameterExpression` objects are read.  This requires us to detect the
version of Terra in use, and use the correct internal QPY reader for the
format version.
Fix #59
=> Fix JSON decoding of Parameters in Terra 0.19.1

qiskit_ibm_runtime/api/clients/runtime.py
This PR adds the following backend related functions to `RuntimeClient`.
- list_backends
- backend_configuration
- backend_status
- backend_properties
- backend_pulse_defaults
Fixes #
=> Add backend related functions in RuntimeClient

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/hub_group_project.py, qiskit_ibm_runtime/ibm_backend.py, qiskit_ibm_runtime/ibm_runtime_service.py
This PR builds upon https://github.com/Qiskit/qiskit-ibm-runtime/pull/55 (will rebase this once #55 is merged) to make the following functionality available to IBM Cloud users. (Currently works only with staging env)
- backends()
- get_backend()
- backend.status()
- backend.properties()
- backend.defaults()
- backend.configuration()
Example:
```python
from qiskit_ibm_runtime import IBMRuntimeService
service = IBMRuntimeService(auth="cloud", token="<staging_api_key>", locator="<staging_locator>")
service.backends()
simulator = service.get_backend("ibmq_qasm_simulator")
simulator.status()
simulator.properties()
simulator.configuration()
simulator.defaults()
```
Fixes #
=> Add support for viewing backends available on IBM Cloud

test/utils/decorators.py
`TestIBMBackend` has been failing because `ibmq_berlin` status could not be retrieved. While this appears to be a server-side issue, the tests probably should use only devices within the specified h/g/p. 
Fixes #
=> Use only backends in specified instance

docs/test/Runtime 0.1.ipynb
I've added acceptance criteria for the Runtime 0.1 - Authentication https://github.com/Qiskit/qiskit-ibm-runtime/issues/2 epic. Will update this file for other epics in separate PRs.
Fixes #
=> Acceptance Criteria for Authentication Epic

qiskit_ibm_runtime/accounts/account.py, qiskit_ibm_runtime/accounts/management.py, qiskit_ibm_runtime/accounts/storage.py, qiskit_ibm_runtime/ibm_runtime_service.py, test/test_account.py, test/utils/account.py
This PR includes the following
**Mainline**
**Tests**
Finalizes account management functionality by filling gaps to meet the acceptance criteria proposed via https://github.com/Qiskit/qiskit-ibm-runtime/pull/58.
=> Finalize account management functionality

qiskit_ibm_runtime/ibm_runtime_service.py, test/test_account.py, test/test_integration_job.py, test/test_proxies.py
`ibmq_berlin` has been retired but continue to be reported by the server as a valid backend. This PR skips `ibmq_berlin`, so tests won't keep tripping over it until that's fixed. 
Since I'm trying to get all tests to pass, this PR also
- closes https://github.com/Qiskit-Partners/qiskit-ibm/issues/226 ,  by deleting the malformed url from the test case. The `http:{}:{}` format was no longer supported in `requests` 2.26+, and I don't see why we need to support it especially since this is a new repo (sorry @daka1510, I know you were dying to fix this one lol)
-  fixes `test_save_get`
=> Don't use ibmq_berlin

.github/workflows/cron-prod.yml, .github/workflows/cron-staging.yml
Fixes the environment variable used to set the staging cron job. 
Fixes #
=> Fix staging cron job env var

test/test_integration_job.py
`test_retrieve_jobs_limit` [occasionally fails](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4733818448?check_suite_focus=true#step:5:2306). I think it's because the test case was getting jobs submitted by other tests and therefore the retrieved jobs were not among those submitted by it. 
This PR adds `program_id` as a filter to ensure it only gets its jobs (`program_id` is unique for each test class).
Fixes #
=> Fix test_retrieve_jobs_limit

test/test_integration_backend.py, test/test_integration_job.py, test/test_integration_program.py
`test_retrieve_jobs_by_program_id` [failed](https://github.com/jyu00/qiskit-ibm-runtime/runs/4739461871?check_suite_focus=true#step:5:3389). While I suspect it's because a retry on POST created a phantom job on the server side, it's difficult to prove without more info. This PR adds debug messages for asserts that may be difficult to debug. 
Fixes #
=> Add more debug messages in test cases

test/test_integration_job.py, test/utils/utils.py
Test cases that cancel a running job can [fail](https://github.com/Qiskit/qiskit-ibm-runtime/runs/4739824168?check_suite_focus=true#step:5:2651) if the job has already finished. This PR adds a utility function that logs a warning and exits the test case if the cancel failed due to job already finished. 
Fixes #
=> Don't raise if cancel failed because job is done

.github/workflows/cron-slow-terra-main.yml
Slow test is usually more stable than slow test against terra main, having them both under same file gives impression that slow tests are always failing in the github UI, so separating them gives better visibility.
=> Separating slow test terra main

docs/apidocs/ibm-runtime.rst, docs/apidocs/ibm_utils.rst, qiskit_ibm_runtime/jupyter/__init__.py, qiskit_ibm_runtime/visualization/interactive/error_map.py, qiskit_ibm_runtime/visualization/interactive/gate_map.py, releasenotes/notes/filter-jobs-by-provider-dead04faaf223840.yaml
- Hide dashboard for initial release
- Remove hub, group and project parameters for IBMRuntimeService in docs
- No need to make utils public in docs
Fixes #
=> Fix documentation issues

README.md, qiskit_ibm_runtime/hub_group_project.py, qiskit_ibm_runtime/ibm_runtime_service.py, qiskit_ibm_runtime/jupyter/__init__.py, qiskit_ibm_runtime/test/ibm_provider_mock.py, qiskit_ibm_runtime/visualization/interactive/error_map.py, qiskit_ibm_runtime/visualization/interactive/gate_map.py, releasenotes/archive/0.12/backend-run-circuits-ad446ca9b56209b9.yaml, test/test_backend_retrieval.py, test/test_integration_backend.py
Rename get_backend to backend
Fixes #
=> Rename get_backend to backend

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/ibm_runtime_service.py, test/ibm_test_case.py, test/mock/fake_runtime_client.py, test/test_integration_job.py, test/test_jobs.py, test/utils/decorators.py
This PR adds code to allow a program to run on cloud runtime without having a backend specified. The server will automatically pick a backend and return the name. 
Fixes #
=> Allow running a program without backend on cloud

test/test_integration_program.py
`test_retrieve_unauthorized_program_data` uses a hard coded program id `sample-program`, which is no longer available on cloud runtime. This PR fixes that by selecting a public program. 
Fixes #
=> Fix missing program in test

qiskit_ibm_runtime/__init__.py, qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/ibm_runtime_service.py, qiskit_ibm_runtime/runtime_options.py, test/ibm_test_case.py, test/mock/fake_runtime_client.py, test/test_integration_job.py, test/test_jobs.py, test/utils/program.py, test/utils/templates.py
Allow users to set a logging level when running a program.
@daka1510 Sorry for taking another one from you, but I need this to get some performance numbers. 
Fixes #11
This PR adds a new `RuntimeOptions` class for the execution options, including `backend_name`, `image`, and now `log_level`. Since we already have `options` as a parameter to `run()`, it made more sense to me to have both `image` and `log_level` in it instead of creating more parameters, especially since they're both related to the execution environment.
=> Allow users to set a logging level when running a program

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/ibm_runtime_service.py, test/test_integration_job.py
`/logout` as a public endpoint is being removed. This PR removes the corresponding code. 
Fixes #
=> Remove logout

qiskit_ibm_runtime/accounts/management.py, test/test_account.py
Make sure environment variables relied on by consumers of the library are consistently named. I.e. use (`QISKIT_IBM_TOKEN`, `QISKIT_IBM_URL`, `QISKIT_IBM_INSTANCE`) instead of (`QISKIT_IBM_API_TOKEN`, `QISKIT_IBM_API_URL`, `QISKIT_IBM_INSTANCE`.
- documentation will follow in a separate PR that @jyu00 is working on
- updating test cases will follow via [separate efforts](https://github.com/Qiskit/qiskit-ibm-runtime/issues/30) (the environment variables used for test cases are mostly implementation details)
=> Use consistently named environment variables

.github/workflows/main.yml, .github/workflows/pr.yml, Makefile, requirements-dev.txt, setup.cfg
Create test coverage reports for unit and integration tests. HTML reports are uploaded as workflow artifacts when the `PR-Test` or `Push-Test` workflows run.
This makes it easy to review current coverage metrics. Let's add the "fancy stuff" (e.g. trends over time, central place to check, badge in README) via [follow-up efforts](https://github.com/Qiskit/qiskit-ibm-runtime/issues/22).
Related to https://github.com/Qiskit/qiskit-ibm-runtime/issues/109
=> Enable test coverage reports

qiskit_ibm_runtime/api/session.py
See https://github.com/Qiskit/qiskit-ibm-runtime/issues/74#issuecomment-1014537885 for background information on the proposed solution.
https://github.com/Qiskit/qiskit-ibm-runtime/issues/74, i.e. avoids `TypeErrors` when scripts finish or interactive python sessions are aborted.
=> Ignore errors during session cleanup

qiskit_ibm_runtime/ibm_runtime_service.py
See https://github.com/Qiskit/qiskit-ibm-runtime/issues/115 for details.
Fixes https://github.com/Qiskit/qiskit-ibm-runtime/issues/115
=> Do no longer fail when `IBMRuntimeService.run` is invoked without providing options

docs/apidocs/ibm-runtime.rst, docs/apidocs/ibm_jupyter.rst, docs/apidocs/ibm_visualization.rst
Exclude `jupyter` and `visualization` from public API documentation.
Fixes https://github.com/Qiskit/qiskit-ibm-runtime/issues/111 (via Option 2)
=> Exclude `jupyter` and `visualization` from public API documentation

README.md, qiskit_ibm_runtime/accounts/__init__.py, qiskit_ibm_runtime/accounts/account.py, qiskit_ibm_runtime/accounts/exceptions.py, qiskit_ibm_runtime/accounts/management.py, qiskit_ibm_runtime/accounts/storage.py, qiskit_ibm_runtime/ibm_runtime_service.py, test/test_account.py
- avoid that an existing account is overwritten unless explicitly specified (raise `AccountAlreadyExistsError` otherwise)
- raise dedicated error classes in other account management related failure cases, i.e.
- `InvalidAccountError` instead of `ValueError`
- `AccountNotFoundError` instead of `ValueError`
Fixes https://github.com/Qiskit/qiskit-ibm-runtime/issues/117 and implements related improvements.
- reached out to Beccy and @rathishcholarajan
=> Improve account management error handling

test/test_basic_server_paths.py
Change makes sure to run pulse tests only against pulse backends. Needed for staging where simulators pretend to be real backends but don't have pulse defaults.
Fixes broken integration tests against legacy-staging
```
FAIL: test_device_properties_and_defaults (test.test_basic_server_paths.TestBasicServerPaths) (hgp='***')
Test device properties and defaults.
----------------------------------------------------------------------
File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/test_basic_server_paths.py", line 55, in test_device_properties_and_defaults
self.assertIsNotNone(pulse_backends[0].defaults())
AssertionError: unexpectedly None
```
=> Fix staging integration tests against legacy environment

.pylintrc, qiskit_ibm_runtime/jupyter/dashboard/dashboard.py, qiskit_ibm_runtime/utils/json.py, qiskit_ibm_runtime/version.py, test/test_data_serialization.py, test/test_tutorials.py, test/utils/utils.py
I'm indifferent about most of the remaining rules, but this PR takes care of : 
`invalid-name`, `super-with-arguments`, and `bad-mcs-classmethod-argument` 
Highlighted the remaining rules in a comment [here](https://github.com/Qiskit/qiskit-ibm-runtime/issues/42#issuecomment-1026077843)
Fixes part of #42
=> Enable disabled pylint rules pt. 2

.pylintrc, qiskit_ibm_runtime/accounts/storage.py, qiskit_ibm_runtime/ibm_runtime_service.py, qiskit_ibm_runtime/version.py, test/test_logger.py, test/test_tutorials.py
Indifferent about the remaining rules, this PR takes care of:
`unspecified-encoding`
`consider-using-with`: should probably stay disabled - there are cases where using `with` is not necessarily beneficial 
`raise-missing-from`: not every exception needs `from`, and adding `from None` seems too verbose 
Fixes part of #42
=> Enabled disabled pylint rules pt.3

test/test_integration_backend.py
See https://github.com/Qiskit/qiskit-ibm-runtime/runs/5061940445?check_suite_focus=true for details. Skip pulse test for backends on staging that do not support pulses.
```
FAIL: test_backend_pulse_defaults (test.test_integration_backend.TestIBMBackend) (backend='backend1')
Check the backend pulse defaults of each backend.
----------------------------------------------------------------------
File "/home/runner/work/qiskit-ibm-runtime/qiskit-ibm-runtime/test/test_integration_backend.py", line 81, in test_backend_pulse_defaults
self.assertIsNotNone(backend.defaults())
AssertionError: unexpectedly None
```
Stabilize legacy-staging integration tests
One more issue left... :)
=> Fix last remaining issue in legacy-staging integration tests

.github/workflows/ci.yml, Makefile, requirements-dev.txt
Enable Coveralls integration. See below links for details.
- [Coveralls Github Action](https://github.com/marketplace/coveralls)
- [Coveralls Github Action Source](https://github.com/coverallsapp/github-action)
Inspired by other open source Qiskit libraries that already integrate with Coveralls (https://coveralls.io/github/Qiskit)
Partially solves #22. We should discuss adding a code coverage badge to the README once this PR is integrated to fully solve it.
=> Enable automated code coverage reports via coveralls.io

.github/workflows/ci.yml, .github/workflows/e2e-tests.yml, .github/workflows/integration-tests.yml, Makefile
Limit collection of coverage metrics to unit tests only.
Agreed with team of key contributors (@rathishcholarajan, @kt474) that we we want to start with coverage metrics for unit tests only. 
This avoids that PR comments like [this](https://github.com/Qiskit/qiskit-ibm-runtime/pull/148#issuecomment-1040455772) report decreased test coverage (because we compare the aggregated coverage of unit tests & integration tests (run for push events) against the coverage for unit tests only (run for pull_request events).
=> Only report coverage metrics for unit tests

docs/tutorials/02_introduction_legacy_runtime.ipynb, docs/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.ipynb, qiskit_ibm_runtime/__init__.py, qiskit_ibm_runtime/ibm_runtime_service.py, qiskit_ibm_runtime/runtime_job.py, releasenotes/notes/stream-results-6ff5f240bbe21fc0.yaml, test/integration/test_interim_results.py, test/unit/test_runtime_ws.py
Final result is also streamed now after interim results when you specify a ``callback``
to `qiskit_ibm_runtime.IBMRuntimeService.run` or `qiskit_ibm_runtime.RuntimeJob.stream_results` methods.
Fixes #146
=> Final result is also streamed now along with interim results

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, README.md, docs/apidocs/ibm-runtime.rst, docs/conf.py, docs/index.rst, qiskit_ibm_runtime/__init__.py, setup.py, test/ibm_test_case.py
1. For repo names we stick with the pattern (since we have already suggested this to partners):
```
qiskit-ibm-runtime
qiskit-dell-runtime
qiskit-ionq-runtime
qiskit-aqt-runtime
```
2. For usage as title in README/Documentation:
```
Qiskit Runtime IBM Quantum Client
Qiskit Runtime Dell Client
Qiskit Runtime IonQ Client
Qiskit Runtime AQT Client
```
3. For usage as description:
```
IBM Quantum Client for Qiskit Runtime
Dell Client for Qiskit Runtime
IonQ Client for Qiskit Runtime
AQT Client for Qiskit Runtime
```
Note: These are called `Client` and not `Provider` because they don't implement the Qiskit `Provider` interface.
4. A `Client` uses a `Service` class to connect to the API. Ex: `IBMRuntimeService`.
```
from qiskit_ibm_runtime import IBMRuntimeService
```
Similarly we could have …
=> Fix branding

docs/release_notes.rst
This commit sets an explicit branch on the reno directive for the docs
build. Without this for the first 0.1.0 release the reno history search
is incorrectly treating the stable/0.1 branch as the origin point for
the history and it is not finding any of the release notes for 0.1
because it's not before the branch point of the stable branch. To fix
workaround this issue, this commit explicitly sets the branch to use for
the release notes to main, this will work only for docs builds on main
as it might have unintended consequences for stable patch releases. We
might need to revert this if/when a 0.1.1 release goes out to ensure the
history scan finds stable branch release notes.
=> Set an explicit branch on release notes directive

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/sampler.py, releasenotes/notes/fix-error-single-circuit-89a0e7b64deedbaa.yaml, test/integration/test_ibm_sampler.py
Fix error when just one QuantumCircuit is passed to primitives
I will be authoring unit tests for most of the scenarios as a separate task and hence don't want to cover this scenario in integration test for estimator.
Fixes #219
=> Fix error when just one QuantumCircuit is passed to primitives

test/integration/test_sampler.py
Check if sampler result for bell circuit always falls within a certain range.
Read more about Bell state [here](https://qiskit.org/textbook/ch-gates/multiple-qubits-entangled-states.html#3.2-Entangled-States-).
#252 
Will open separate PR for estimator in order to close this issue.
=> Check if sampler result for bell circuit always falls within a certain range

docs/tutorials/how-to-getting-started-with-estimator.ipynb, docs/tutorials/how-to-getting-started-with-sampler.ipynb
The bullet points under [Specify program inputs](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/how-to-getting-started-with-estimator.html#Specify-program-inputs) in the two how-to guides are not rendered correctly.
This is possibly due to the bullet points are created by `*` instead of `-` in markdown. This PR replace `*` with `-` in an attempt to fix it. I need to build the website locally to verify this actually fixes the problem.
EDIT: The problem could be due to missing empty line before the bullets instead. I added that in the second commit. At least ReviewNB renders the bullet point correctly.
Fixes #
=> Fix how-to guide bullet points

docs/conf.py
The github links at the top of tutorials right now points to the tutorials in a release tag. Docs are usually ready only after releasing the library. Once docs are ready the stable branch can be updated with the doc changes. This PR makes the tutorial links to point to the stable branch instead of the tag so that links are not broken anymore when docs are deployed to qiskit.org and updated in stable branch.
I have now updated stable/0.4 branch with the latest docs and tutorials.
Fixes #286
=> Point tutorial links to stable branch instead of tag

docs/tutorials/sample_expval_program/qiskit_runtime_expval_program.ipynb, qiskit_ibm_runtime/sampler.py
This fixes the spelling of probabilities in a few places (each case where this particular misspelling occurred).
=> Fix spelling of probabilities

docs/tutorials/05_uploading_program.ipynb, docs/tutorials/sample_expval_program/qiskit_runtime_expval_program.ipynb, docs/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.ipynb
Import UserMessenger and ResultDecoder from program module. The program module might get deprecated in the near future when we support only primitives. That's why I don't want these classes to be directly imported from qiskit_ibm_runtime.
Fixes #208
Fixes #321
=> Fix UserMessenger and ResultDecoder imports in tutorials

docs/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.ipynb, docs/tutorials/sample_vqe_program/sample_vqe.py
This fixes the spelling of "interim" in the VQE sample program.
=> Fix spelling of "interim" in the VQE sample program

qiskit_ibm_runtime/exceptions.py, qiskit_ibm_runtime/runtime_job.py, releasenotes/notes/upgrade-runtime-job-timeout-error-3e01617412bbc37f.yaml, test/integration/test_results.py
Raise `RuntimeJobTimeoutError` when `timeout` expires for `result()` or `wait_for_final_state()`.
Fixes #316
=> Raise RuntimeJobTimeoutError

qiskit_ibm_runtime/hub_group_project.py, qiskit_ibm_runtime/ibm_backend.py, qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/add-service-property-d6a076214c131d7a.yaml, test/integration/test_backend.py, test/unit/mock/fake_runtime_service.py
The ``service`` object which is an instance of `QiskitRuntimeService`
class can now be accessed from `IBMBackend` class using the ``service``
property.
Ex:
```python
backend = service.get_backend("ibmq_qasm_simulator")
backend.service  # QiskitRuntimeService instance used to instantiate the backend
```
Fixes #300
=> Add service property to IBMBackend class

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/max-execution-time-ecdb69210afe3d89.yaml, test/ibm_test_case.py, test/integration/test_job.py, test/program.py, test/unit/mock/fake_runtime_client.py
=> Add max_execution_time to service.run

qiskit_ibm_runtime/runtime_job.py
The result is empty (due to admin manually cancelling a hung job) and hence when trying to decode empty result, we get below json decode error. This PR checks if the result is not empty before trying to decode.
```
File "/var/folders/9m/2znk9kw163g8bvhxls_v1j1h0000gn/T/ipykernel_1728/1059953898.py", line 40, in <cell line: 34>
print("runtime counts: ",jobt.result().get_counts())
File "/opt/anaconda3/envs/QiskitDevenv/lib/python3.10/site-packages/qiskit/providers/ibmq/runtime/runtime_job.py", line 154, in result
self._results = _decoder.decode(result_raw)
File "/opt/anaconda3/envs/QiskitDevenv/lib/python3.10/site-packages/qiskit/providers/ibmq/runner_result.py", line 31, in decode
return cls.from_dict(json.loads(data))
File …
```
=> Don't try to decode if results are empty

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/api/rest/runtime_session.py, qiskit_ibm_runtime/qiskit_runtime_service.py, qiskit_ibm_runtime/runtime_session.py, test/ibm_test_case.py, test/integration/test_retrieve_job.py, test/unit/mock/fake_runtime_client.py
With the latest session aware scheduling enhancements we have to now explicitly pass the start_session flag to POST /jobs API to start a runtime session.
Also calling DELETE /sessions/{session_id}/close API will close the session.
Testing:
The existing integration tests for estimator and sampler are good enough to test these changes.
Fixes #374 
Fixes #375
=> Pass start_session flag and also call new close session API

qiskit_ibm_runtime/utils/json.py
=> Fix #394: Make import work with Terra dev version

docs/tutorials/how-to-getting-started-with-sampler.ipynb
Updated two typos of `theta` to `theta1` in [how-to-getting-started-with-sampler.ipynb](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/tutorials/how-to-getting-started-with-sampler.ipynb).
Small typos in documents tutorials.
Fixes #400
=> Update Docs: how-to-getting-started-with-sampler.ipynb

docs/conf.py, test/integration/test_job.py
Job no longer queues if an invalid `max_execution_time` is given 
Fixes #
=> Fix custom_max_execution_time test 

qiskit_ibm_runtime/qpy/binary_io/circuits.py, qiskit_ibm_runtime/qpy/binary_io/schedules.py, qiskit_ibm_runtime/qpy/type_keys.py
Was looking for QpyError in the wrong exceptions file.
Fixes #
=> Fix issue "AttributeError: module 'qiskit_ibm_runtime.exceptions' has no attribute 'QpyError'"

qiskit_ibm_runtime/utils/utils.py, test/unit/test_client_parameters.py
Allow developers to run the SDK against internal development clusters like so:
```
service1 = QiskitRuntimeService(
url='https://api-ntc-....experimental-us-....us-east.containers.appdomain.cloud',
channel='ibm_cloud',
token='...',
instance='crn:v1:staging:public:quantum-computing:us-east:a/...',
verify=False
)
service1.backends()
service2 = QiskitRuntimeService.save_account(
name='experimental'
url='https://api-ntc-....experimental-us-....us-east.containers.appdomain.cloud',
channel='ibm_cloud',
token='...',
instance='crn:v1:staging:public:quantum-computing:us-east:a/...',
verify=False
)
service2 = QiskitRuntimeService(name='experimental')
service2.backends()
``` 
In this case, the resolved runtime url should not be updated like in the regular flow where the location identifier from the …
=> Add support for testing SDK against experimental development cluster

releasenotes/notes/fix-terra-min-version-613f427851adfab0.yaml, requirements.txt, setup.py
Bump min terra version to 0.21.0 (since earlier versions are not compatible with latest of qiskit-ibm-runtime).
Fixes #428
=> Bump min terra version to 0.21.0

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/sampler.py
Set optimization level default to 1 for alpha release (will be changed back to 3 if needed post alpha). Also remove resilience levels 2 and 3 for alpha release.
Fixes #
=> Set optimization level default to 1 for alpha release

docs/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.ipynb
Fix a typo in the VQE sample program, `fuction` to `function`.
Fixes #433
=> Fix spelling of "function" in the VQE sample program

docs/tutorials/sample_expval_program/qiskit_runtime_expval_program.ipynb
- Typo
line 84 :  expecation -> expectation
line 127, 448 : devitation -> deviation
line 354 : excute -> execute
line 593 : heavy-ouputs -> heavy-outputs
line 662 : meaasurements -> measurements
lint 688 : expection -> expectation
- Grammer
line 39 : where an user -> where a user
line 66, 534 : the all -> all
line 491 : Lets -> Let's
Fixes #
=> Fix typos in runtime expval notebook

docs/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.ipynb
Fix a typo in the VQE sample program, `implimenting` to `implementing`.
Fixes #439
=> Fix spelling of "implementing" in the VQE sample program

docs/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.ipynb
Fix a wrong attritube of Aer in the qiskit_runtime_vqe_program.ipynb
**Fixes** 
Modify from Aer.backend() to Aer.get_backend()
**Source codes**
```
from qiskit import Aer
backend = Aer.backend("qasm_simulator")
```
**Error messages**
```
Input In [5] in <cell line: 4>
backend = Aer.backend("qasm_simulator")
File /opt/conda/lib/python3.8/site-packages/qiskit/__init__.py:126 in __getattr__
return getattr(self.aer, attr)
AttributeError: 'AerProvider' object has no attribute 'backend'
Use %tb to get the full traceback.
```
=> Fix issue - "AttributeError: 'AerProvider' object has no attribute" in the qiskit_runtime_vqe_program.ipynb

qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/refactor-caching-programs-c49b517df7d2f702.yaml
Instead of caching all programs on the first call to `service.programs()`, only cache up to `limit` (which defaults to 20). 
```service.programs(limit=None)``` can still be used to retrieve all programs. 
This seems like a better solution than removing caching altogether because the api has a hidden limit of 20 programs retrieved at a time.
Fixes #451
=> Avoid caching all programs 

qiskit_ibm_runtime/accounts/management.py, releasenotes/notes/parameterize-service-channel-d14de7391dfb5ee1.yaml, test/unit/test_account.py
``channel`` can now be stored as an environment variable so the service does not have to be instantiated manually and instead can be created from the env variables.
Example: 
```
from qiskit_ibm_runtime import Sampler
import os
os.environ["QISKIT_IBM_CHANNEL"] = channel
os.environ["QISKIT_IBM_TOKEN"] = token
os.environ["QISKIT_IBM_INSTANCE"] = instance
os.environ["QISKIT_IBM_URL"] = url
with Sampler(...) as sampler:
result = sampler(...)
```
Fixes #444
=> Specify service parameter channel through env variable

qiskit_ibm_runtime/utils/backend_converter.py
The `apply_prefix` method [here](https://github.com/Qiskit/qiskit-terra/blob/beea6f0f2de0aa8f0484fb14c5024f22c0b5b715/qiskit/providers/models/backendproperties.py#L200) in `BackendProperties` is already converting to seconds and hz
Fixes #
=> Remove unnecessary qubit property conversions 

qiskit_ibm_runtime/estimator.py
This PR converts `ExpectationValues.results` into ndarray if necessary to be compatible with the [definition](https://github.com/Qiskit/qiskit-terra/blob/cf951202c77b49d28e7d23f43088b191638f282a/qiskit/primitives/estimator_result.py#L43).
The job page of IQX dashboard displays binary data as expectation values.
I'm working on make the values as a list of float values. So, we need to convert them back to ndarray to construct `EstiamtorResult`.
=> Convert `EstimatorResult.values` to ndarray if necessary

qiskit_ibm_runtime/api/session.py
Different env variables are used for the custom client header in ibmq provider and the runtime provider. The qiskit version returned is unaffected, this will make sure the custom client header (if it exists) is appended.
```
CUSTOM_HEADER_ENV_VAR = 'QE_CUSTOM_CLIENT_APP_HEADER'
CUSTOM_HEADER_ENV_VAR = "QISKIT_IBM_RUNTIME_CUSTOM_CLIENT_APP_HEADER"
```
Fixes #460
=> Check ibmq provider custom client header env variable 

requirements.txt, setup.py
On 8/24 websocket-client 1.4 was released and since then, the `test_websocket_proxy` test case has been failing on cloud. For now we can avoid this version and use 1.3.3 instead. 
Fixes #508
=> Set websocket-client version

qiskit_ibm_runtime/sampler.py
#455 converted `SamplerResult.quasi_dists` from dict to `QuasiDistribution` to match the `SamplerResult` description. That PR was written before we deprecated `_call` and moved to `_run`, so it only applied to the old path. It is also why the latest integration test failed.
This PR moved that code to `SamplerResultDecoder`, which does result processing when `job.result()` is called. 
@t-imamichi Are you ok if I use the old code in the old path - i.e. the result returned by `_call()` will be `SamplerResult` with a list of dict instead of `QuasiDistribution`? This way it's no longer a breaking change, and people using the new `run()` method will get the correct output (list of `QuasiDistribution`). 
Fixes #
=> Move conversion of QuasiDistribution to result decoder

qiskit_ibm_runtime/utils/backend_converter.py
This commit adds a missing Delay operation to the target for backends. All the IBM backends have a delay instruction in the basis gates, but in the case of backends with a properties payload defined the basis gates is not looked at for the more rich data set available in the properties payload. This means the delay instruction which is not present in the properties is not included in the output target. This causes compilation with any circuit containing a delay to fail because it's not in the target instruction set for the backend. This commit fixes this by ensuring all backends have delay defined for all backends regardless of how instructions are parsed.
This commit is effectively a port of Qiskit/qiskit-ibm-provider#351 and Qiskit/qiskit-ibm-provider#346
Co-authored-by: Kevin Tian …
=> Add missing Delay instructions to Target

requirements-dev.txt
There was an update to `sphinx-autodocs-typehints` today that seems to have broken our docs build 
broken build [here](https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/3131462331/jobs/5082827492)
https://github.com/tox-dev/sphinx-autodoc-typehints/releases/tag/1.19.3
Fixes #
=> Fix docs build 

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/sampler.py, qiskit_ibm_runtime/session.py, releasenotes/notes/primitives-callback-80a7c2dcda960f4d.yaml, test/integration/test_estimator.py, test/integration/test_sampler.py, test/unit/test_runtime_ws.py
Allow users to specify a callback function to stream interim results, such as error mitigation progress, of primitives. 
Fixes #504
=> Add callback to primitive interface

docs/how_to/retrieve_job_results.ipynb, releasenotes/notes/fix-howto-retrieve-job-ef991e8d6b444096.yaml
The "how to retrieve job result" how-to guide had a `TODO: link to how to retrieve job`, and there isn't actually a guide on retrieving jobs. 
This PR replaces that TODO with actual steps on retrieving a job. 
Fixes #
=> Fix TODO in howto doc

qiskit_ibm_runtime/options.py, test/unit/test_options.py
Fix a bug in `Options._from_dict` where it only looked at `image` and ignored the other options. 
Fixes #
=> Fix environment options in from_dict

qiskit_ibm_runtime/qiskit_runtime_service.py
`qrt_options.instance` should be passed in instead of `instance`
Currently, this wouldn't use the correct instance 
```python
options = Options(environment= {'instance':'ibm-q/open/main'})
with Session(service=service, backend="ibmq_qasm_simulator") as session:
sampler = Sampler(session=session, options=options)
job = sampler.run(...)
```
=> Pass in correct instance in service.run()

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/options.py, qiskit_ibm_runtime/sampler.py, test/unit/test_runtime_ws.py
Move the `callback` parameter to the `Options` class to keep `run()` more consistent with the base classes. 
Fixes #
=> Move callback to Options

qiskit_ibm_runtime/ibm_backend.py, releasenotes/notes/0.7/add-backend-run-911bda849f637ca0.yaml, test/integration/test_backend.py
After some discussion with @tmittal947 we thought it's better not add `backend.run()` in `qiskit-ibm-runtime` for a number of reasons:
1. It's not supported by all channels
2. `qiskit-ibm-runtime` is supposed to focus on the "managed services" experience, and `backend.run()` is the opposite of that. Instead, any need of direct access should be done using the new `qiskit-ibm-provider`.
3. It's confusing to users when we have `backend.run()` in both `qiskit-ibm-runtime` and `qiskit-ibm-provider`. 
Sorry @kt474 
Fixes #
=> Remove backend.run

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/sampler.py
The primitive programs on the server side do this and hence no need to pass from client.
Should fix below error when running circuit from #568:
```
File "/code/program.py", line 1158, in main\n
2022-10-10T13:20:37.811939030Z     result = estimator.run(\n
2022-10-10T13:20:37.811959070Z   File "/code/program.py", line 207, in run\n
2022-10-10T13:20:37.812024750Z     self._validate_parameters(\n
2022-10-10T13:20:37.812041987Z   File "/code/program.py", line 585, in _validate_parameters\n
2022-10-10T13:20:37.812278740Z     raise QiskitError(\n2022-10-10T13:20:37.812298997Z qiskit.exceptions.QiskitError: \'Different number of parameters (15) and circuits (60).\'\n'
```
Fixes #
=> No need to pass parameters from client

qiskit_ibm_runtime/runtime_job.py
A `sleep()` was added to `job.wait_for_final_state` because job status may not become final when websocket is closed. But sleeping for 3s seems a bit excessive and is really hurting our performance numbers. 
Fixes #
=> Sleep less when polling for status

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/options/options.py, qiskit_ibm_runtime/sampler.py, test/unit/test_ibm_primitives.py
The old `options` parameter in `Sampler` and `Estimator` constructors [allowed `log_level` to be specified](https://github.com/Qiskit/qiskit-ibm-runtime/blob/0.6.2/qiskit_ibm_runtime/sampler.py#L58-L60). Since `log_level` is now under `environment`, we should still accept it with a deprecation warning. 
It also allowed `image`, which is now an implicit option but still needs to be copied to runtime options.
Fixes #
=> Fix log_level from old options

docs/tutorials/how-to-getting-started-with-estimator.ipynb, docs/tutorials/how-to-getting-started-with-sampler.ipynb
`callback` was moved into `Options` to make `run()` more consistent with the base classes. This PR updates the tutorials which still referenced `callback` as a parameters to `run()`. 
Fixes #
=> Remove callback from tutorial doc

qiskit_ibm_runtime/__init__.py, qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/sampler.py, qiskit_ibm_runtime/utils/estimator_result_decoder.py, qiskit_ibm_runtime/utils/sampler_result_decoder.py, releasenotes/notes/upgrade-terra-80a543c559e259ce.yaml, requirements.txt, setup.py, test/integration/test_estimator.py, test/integration/test_sampler.py, test/integration/test_session.py, test/unit/test_data_serialization.py, test/unit/test_estimator.py, test/unit/test_ibm_primitives.py, test/unit/test_sampler.py
Since `qiskit-terra` 0.22 was released, we can use the base primitives from it. Unfortunately we still need the local `_circuit_key` which is not in the 0.22 release. 
Fixes #567 
Putting in draft until I can confirm it works with QRT primitives (waiting on the Sampler fix)
=> Use base primitives from terra 0.22

test/integration/test_job.py
This test case fails intermittently - simple fix is to increase the sleep per iteration time to make sure the job does not run
```
FAIL: test_run_program_failed_ran_too_long (test.integration.test_job.TestIntegrationJob) (service=<QiskitRuntimeService>)
Test a program that failed since it ran longer than maximum execution time.
----------------------------------------------------------------------
File "/Users/kt/Documents/qiskit-ibm-runtime/test/decorators.py", line 69, in _wrapper
func(self, *args, **kwargs)
File "/Users/kt/Documents/qiskit-ibm-runtime/test/integration/test_job.py", line 112, in test_run_program_failed_ran_too_long
self.assertEqual(JobStatus.ERROR, job.status())
AssertionError: <JobStatus.ERROR: 'job incurred error'> != …
```
=> Fix test_run_program_failed_ran_too_long

test/integration/test_estimator.py, test/integration/test_results.py, test/integration/test_sampler.py
`test_websocket_proxy` has been failing because jobs are so much faster now 😁 that it finishes before websocket connection (through proxy) can be done. 
Update: Did the same for `test_estimator_callback` and `test_sampler_callback`. 
Related to #584
=> Increase job time for callback tests

qiskit_ibm_runtime/options/options.py, test/unit/test_ibm_primitives.py
This fixes a bug where when `image` is specified, it's passed to program inputs in addition to runtime options.
Fixes #
=> Remove image from inputs

qiskit_ibm_runtime/session.py, releasenotes/notes/use-backend-service-020daf6e4a4d044e.yaml, test/unit/test_session.py
If I pass an `IBMBackend` instance to `Session` constructor, the service used to initialize the backend instance should be used for the session, if no other `service` parameter is passed. 
Fixes #
=> Use backend service in session if known

qiskit_ibm_runtime/options/__init__.py, qiskit_ibm_runtime/options/options.py, qiskit_ibm_runtime/options/resilience_options.py, releasenotes/notes/resilience_settings-80eb23a095f0381c.yaml, test/unit/test_options.py
Add advanced resilience options. 
Fixes #595
=> Advanced resilience options

qiskit_ibm_runtime/session.py
The Session.session_id is None until the first job in the session is run since it implicitly creates the session and sets the session_id from that. This is a bit confusing though if you do something like this and expect something other than None:
```python
with Session(service=service) as session:
print(f"Session id: {session.session_id}")
```
n/a
=> Update docstring for session_id

qiskit_ibm_runtime/runtime_job.py
For a python docstring if it's multiple lines there should be a first line and then a break with a paragraph for additional wording, otherwise it doesn't get formatted properly as seen here [1].
[1] https://qiskit.org/documentation/partners/qiskit_ibm_runtime/stubs/qiskit_ibm_runtime.RuntimeJob.html#qiskit_ibm_runtime.RuntimeJob
n/a
=> Fix docstring formatting on wait_for_final_state

requirements-dev.txt
sklearn has been deprecated, causing our code quality check build to break 
https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/3595252302/jobs/6054515435#step:4:194
Fixes #
=> Replace sklearn package with scikit-learn

qiskit_ibm_runtime/utils/utils.py
Development cluster URL will no longer have cloud in it so we need to lose the restriction. There should not be any other url that contains "experimental" in it so this check should be good enough.
=> fix: update url for development cluster

qiskit_ibm_runtime/api/rest/runtime.py, releasenotes/notes/post-timeout-a0928a23941f503b.yaml
Increase the timeout value for job submit to 900s. While it's not quite enough to send a 100MB payload, anything more would cause a Cloudflare timeout.
Fixes #497
=> Increase job submit timeout

docs/how_to/error-mitigation.rst
changed "amplifer" to "amplifier"
In "Advanced resilience options" section and in "Example of adding resilience_options into your estimator session" section
the word "amplifier" was typed as "amplifer" this was not letting these options be applied to the Options() from qiskit_ibm_runtime.
So, just changed "Amplifer" to "amplifier"
Fixes #
Now, error mitigation routines are applied correctly in Options() from qiskit_ibm_runtime
=> just a typing error

qiskit_ibm_runtime/runtime_job.py
We recently removed job params from the list jobs endpoint so they may not exist if a user uses `jobs()` and then `job.input` for one of those jobs
integration tests failed [here](https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/4081008276/jobs/7034017990#step:5:1905)
Fixes #
=> Request job params if they don't exist

docs/index.rst, docs/migrate_from_ibmq.rst
I was unable to find a guide to migrate `qiskit-ibmq-provider` classes into the new `qiskit-ibm-runtime`. So I wrote a small equivalence table for the documentation.
It looks like this:
=> Migration guide from qiskit-ibmq-provider

requirements.txt, setup.py
The new jupyterhub upgrade to 3.x will require `websocketclient >= 1.5.1`
Fixes #
=> Update websocket-client version

qiskit_ibm_runtime/accounts/management.py, test/unit/test_account.py
Allow the user to invoke `QiskitRuntimeService.save_account()` without specifying a channel. 
The channel will be set either to the value in environment variable `QISKIT_IBM_CHANNEL` or to `ibm_cloud` in this order.
Fixes #632
=> For save_account, use default channel if the channel is not specified

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/sampler.py, releasenotes/notes/error-lvl-defaults-no-backend-95fba0e99884314a.yaml
As @merav-aharoni mentioned in https://github.com/Qiskit/qiskit-ibm-runtime/pull/748#issuecomment-1484110941, if `self._session.backend()` does not exist, the optimization and resilience levels will be set to `None` which would fail the job.
This could happen on cloud when no backend is selected, or when the sampler/estimator are used as sessions 
tests should be covered in https://github.com/Qiskit/qiskit-ibm-runtime/pull/748
Fixes #
=> Set error levels to default when no backend is selected

qiskit_ibm_runtime/runtime_job.py
There were cases where the check whether the result should be fetched from an external source was missing.
Fixes #
=> Support external results whenever `.job_results()` is called

qiskit_ibm_runtime/runtime_job.py
In some cases, error messages contain an external results URL, in other cases, they don't. This PR introduces a try-except block to catch JSONDecodeErrors. In that case, we'll return the raw result instead of trying to parse it.
Fixes https://github.com/Qiskit/qiskit-ibm-provider/issues/554
=> use try-except block to guard against errors during json parsing. If the

docs/tutorials/Error-Suppression-and-Error-Mitigation.ipynb
A simple typo is fixed in the code.
` -> '
Due to mistyped grave accent ` instead of apostrophe ', the code used to give out SyntaxError: unterminated string literal 
Fixes #
=> fix typo in tutorial code

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/ibm_backend.py, qiskit_ibm_runtime/sampler.py, test/unit/test_ibm_primitives.py, test/utils.py
Closes #792
Checks if the input circuits use a faulty qubit or edge and raises if they do.
Fixes #
=> Check for faulty qubits and edges

docs/getting_started.rst
I received a report from IBM Quantum Marketing:
> [...] On [Getting Started](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/getting_started.html), the “Retrive IBM Cloud token should link here: https://cloud.ibm.com/iam/apikeys
The current link is 404ing.
=> "Retrieve IBM Cloud token" link broken

.github/workflows/e2e-tests.yml
Fixes https://github.com/Qiskit/qiskit-ibm-runtime/pull/824. 
This did not cause the PR CI to fail because the tests happen on a cron schedule.
=> Fix bad CI config for e2e tests

qiskit_ibm_runtime/options/options.py, releasenotes/notes/error_msg_max_execution_time-e401d353ae2a7d86.yaml, test/unit/test_ibm_primitives.py
Added error message when max_execution_time is outside the allowed range. Previously, this gave an error on the server side.
Related to  #851.
Should actually have been part of #781.
=> Error message upon unsupported values for max_execution_time

README.md, docs/cloud/quickstart.rst, docs/compare.rst, docs/getting_started.rst, docs/how_to/options.rst, docs/index.rst, docs/migrate/migrate-guide.rst, docs/primitives.rst, docs/tutorials/grover_with_sampler.ipynb, qiskit_ibm_runtime/__init__.py, qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/options/__init__.py, qiskit_ibm_runtime/options/options.py, qiskit_ibm_runtime/sampler.py
Converting "primitive program" into "primitive" (as a noun). For context, see https://qubit-social.xyz/@blakejohnson/110338831690761969
Additionally,
* I removed the `Hello World` example in the README, assuming it is on its way out. Not fully sure.
* link to https://research.ibm.com/blog/near-real-time-quantum-compute for "near-time"
=> Removing primitive program (and link to near time)

test/unit/test_options.py
`test_coupling_map_options` was failing because of different order of the couples in the list. 
Converted the lists to sets for the comparison.
See also #877
=> Fix CouplingMap test

docs/cloud/plans.rst
We only charge for QR time - remove mentions of classical time in the cost section
Fixes #
=> Charge for QR time only

test/integration/test_job.py
This testing is failing on cloud - I believe the db takes a second to update because the logs should always be returned and this change seems to fix it 
Fixes #
=> Add sleep to test_job_logs

qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/filter_instance-a7203041b5ab85d9.yaml, test/decorators.py, test/unit/test_backend_retrieval.py
When `QiskitRuntimeService()` is initialised with `instance`, filter the backends according to the `instance`.
Previously, the backends were filtered by `instance` only when it was given as parameter to `QiskitRuntimeService.backends()`.
In addition, we now raise an exception if the `instance` parameter to `QiskitRuntimeService` is not supported. Previously, we only  gave a warning.
Fixes #938.
=> Filter backends by instance when given in QiskitRuntimeService constructor

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/sampler.py, releasenotes/notes/remove-data-caching-code-b878a85c3987a947.yaml
#971 should not have been merged (oops), we need to wait for qiskit-ibm-primitives issue 108 first 
The data caching code and related tests can still be removed, just not the `circuit_indicies` and `observable_indicies` inputs
=> Revert circuit/observable indicies removal

test/decorators.py, test/integration/test_job.py, test/integration/test_options.py
Fixing small bug introduced in https://github.com/Qiskit/qiskit-ibm-runtime/pull/979, cloud accounts still need the instance parameter. 
Fixes #
=> Fix decorators initialize service bug in testing suite 

docs/faqs/max_execution_time.rst
Use date on max_execution_time change since it's not related to qiskit-ibm-runtime release. 
Fixes #
=> Use date on max_execution_time change

qiskit_ibm_runtime/base_primitive.py, releasenotes/notes/remove-backend-circuits-limit-b804b58dc97ed276.yaml, test/unit/test_ibm_primitives.py
Reverting #939, because this validation with primitives run in sessions is not actually necessary. 
Fixes #
=> Remove max circuits validation

qiskit_ibm_runtime/options/resilience_options.py, qiskit_ibm_runtime/utils/deprecation.py, releasenotes/notes/deprecate_noise_amplifier-e656cc98a962a81b.yaml, test/unit/test_estimator.py, test/unit/test_ibm_primitives.py, test/unit/test_options.py, test/utils.py
Deprecate `noise_amplifier` resilience option.
Fixes #
=> Deprecate noise amplification option

qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/instances-method-02fda1de98638e59.yaml
To be consistent with `qiskit-ibm-provider`, there should be an `instances()` method that returns all instances the user is in (quantum channel only). 
Fixes #
=> Add instances method 

test/integration/test_estimator.py, test/integration/test_sampler.py
Integration tests currently fail as the expected message changed (case-sensitivity change). This PR should fix it.
Example build exhibiting the error: https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/6096856126/job/16543305033#step:5:1424
As can be seen in the output below, there were some subtle changes in the message we expect in the integration test:
* `REGISTER NAME` (old) vs `register name` (new)
* `NO COUNTS FOR EXPERIMENT` (old) vs `No counts for experiment` (new)
```
======================================================================
ERROR: test_all_resilience_levels (test.integration.test_options.TestIntegrationOptions) (service=<QiskitRuntimeService>)
Test that all resilience_levels are recognized correctly
------------------------------------------------------------- …
```
=> Fix failing integration test due to case-sensitivity change

qiskit_ibm_runtime/options/options.py, qiskit_ibm_runtime/utils/qctrl.py, test/integration/test_job.py, test/unit/test_ibm_primitives.py
=> Remove min execution time check

test/integration/test_options.py
=> Use correct simulator in integration tests

qiskit_ibm_runtime/estimator.py
Partial fix to https://github.com/Qiskit/qiskit-ibm-runtime/issues/1057
Skip importing `PauliSumOp`, which is only used for type hinting.
=> Remove importing PauliSumOp, which is deprecated

qiskit_ibm_runtime/utils/qctrl.py
Corrects default value for optimization level under q-ctrl strategy
Fixes #
Corrects default value for optimization level under q-ctrl strategy, value should be 3, not 1
=> Adjusts default value for optimization_level

README.md
Request from the Support team
Fixes #
=> add instance info

README.md
The link to the `qiskit_ibm_runtime.Options` class was broken.
I updated the link.
=> Fix links to options in README.md

test/unit/test_data_serialization.py
I started looking into the unit tests which trigger `qiskit.opflow` and `qiskit.algorithms` deprecation warnings (see https://github.com/Qiskit/qiskit-ibm-runtime/issues/1057) to see what is the best way to address these, and I think that:
1. the optimizer tests can directly be removed
2. the operator tests don't need to test any opflow class beyond PauliSumOp (which is the only one documented as being supported)
Let me know if I missed anything, but from what I see, these tests are not really actionable unit tests. They are an integration test of sorts to check that common inputs/outputs to the encoder/decoder “work”. However, all the encoder does is call whatever object’s `.to_json` method, which is not runtime’s “responsibility” to fix. I guess that a selection of “common” inputs was …
=> Remove opflow and algorithms from serialization tests

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/channel-strategy-backend-filter-a4fe5248d9aea9c1.yaml, test/unit/mock/fake_runtime_client.py
If a channel strategy is passed in during initialization, only backends supporting that channel strategy will be returned. 
We can add a test when we can test the full Q-CTRL path.
Fixes #1058
=> Only return channel strategy supported backends 

qiskit_ibm_runtime/runtime_job.py, qiskit_ibm_runtime/session.py, test/unit/test_session.py
Removing bss.seconds deprecation warning, it's been 3 months
Removing passing in a backend into options, this was deprecated 9 months ago 
Also replaced `assertDictContainsSubset` because it was removed in python 3.11
Fixes part of #784
=> Remove old deprecations

docs/faqs/max_execution_time.rst, docs/sessions.rst
=> Open plan updates

qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/job-quota-warning-0512f30571897f53.yaml
~~Don't merge until at least 9/26, I need to test this on production~~
Warning returned from /jobs in this format:
```python
{'id': 'cm65ft7e49b0008szmdg', 'backend': 'fake_backend1', 'messages': [{'level': 'warn', 'data': 'Your current pending jobs are estimated to consume 7.329993678195504 quantum seconds, but you only have 1 quantum seconds left in your monthly quota; therefore, it is likely this job will be canceled'}]}
```
Fixes #1088
=> Warn users if job submitted will exceed quota

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/qiskit_runtime_service.py, test/integration/test_backend.py, test/unit/test_logger.py, test/utils.py
=> Fix minor todos

docs/cloud/cost.rst, docs/faqs/max_execution_time.rst, qiskit_ibm_runtime/options/options.py, qiskit_ibm_runtime/runtime_job.py, qiskit_ibm_runtime/runtime_options.py, releasenotes/notes/0.11/job-cost-estimation-d0ba83dbc95c3f67.yaml, releasenotes/notes/0.12/max-execution-time-definition-196cb6297693c0f2.yaml, releasenotes/notes/job-quota-warning-0512f30571897f53.yaml
Wording changes suggested by @jyu00 and @abbycross 
Fixes #
=> Change qpu complex wording

qiskit_ibm_runtime/exceptions.py, test/unit/mock/fake_runtime_client.py
I only identified one such exception - as @jyu00 pointed out - `RuntimeJobFailureError` should inherit `JobError`.
While reviewing the exceptions, I changed the exception type in the `fake_runtime_client`. I thought `QiskitBackendNotFoundError` was more suitable here.
Fixes #1118
See also https://github.com/Qiskit/qiskit-ibm-provider/pull/741.
=> Exceptions should inherit from Terra where suitable

qiskit_ibm_runtime/session.py
=> Update docstring & remove max_time in `from_id()`

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/api/rest/base.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/api/rest/runtime_session.py, qiskit_ibm_runtime/session.py, releasenotes/notes/expose-session-details-c4a44316d30dad33.yaml
Adding a new `session.details()` method that returns the following:
Both channels will return these 11 fields:
```python
{
'id': 'cki5d18m3kt305s4pndg',
'backend_name': 'ibm_algiers',
'interactive_timeout': 300,
'max_time': 28800,
'active_ttl': 28800,
'state': 'closed',
'accepting_jobs': True,
'last_job_started': '2023-10-09T19:37:42.004Z',
'last_job_completed': '2023-10-09T19:38:10.064Z',
'started_at': '2023-10-09T19:37:42.004Z',
'closed_at': '2023-10-09T19:38:39.406Z'
}
```
Also added `runtime_session.py` and `base.py` back to this repo since we are eventually merging qiskit-ibm-provider back here anyway.
Fixes #887 
~~Also, open to different options on how we want these new details exposed. Do we want just a method that returns all the information, or maybe specific properties added to …
=> Expose new session details 

qiskit_ibm_runtime/ibm_backend.py, releasenotes/notes/target-history-date-bug-7d6dad84fc5b3d2e.yaml, test/integration/test_backend.py
There was an issue where passing in a `datetime` to `target_history()` wouldn't actually use the backend properties from the specified date 
```python
dt1 = datetime(2023, 9, 25, 20, 55, 55, tzinfo=timezone.utc)
th1 = backend.target_history(dt1)
dt2 = datetime(2023, 10, 9, 20, 55, 55, tzinfo=timezone.utc)
th2 = backend.target_history(dt2) # should be different from th1
```
Fixes #
=> Fix target_history date bug 

qiskit_ibm_runtime/utils/json.py, releasenotes/notes/fix_np_int64-864b605a88f57419.yaml, test/unit/test_data_serialization.py
Added support for `numpy.int64` in the `RuntimeEncoder`.
Fixes - same as https://github.com/Qiskit/qiskit-ibm-provider/issues/743 for Runtime repo.
=> Fixed bug when defining shots as int64

qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/log-instance-selected-a18c4791418b5e0d.yaml, test/integration/test_account.py
At initialization, if not passed in directly, the default `instance` selected by the provider 
will be logged at the "INFO" level. When running a job, if the backend selected is not in 
the default instance but in a different instance the user also has access to, that instance 
will also be logged.
Fixes #1126
=> Log instance on initialization and when running a job

docs/_templates/autosummary/class.rst, qiskit_ibm_runtime/ibm_backend.py
Moved all the methods into class pages to speed up the building process of the documentation with the new ecosystem sphinx theme. This change helps with this [PR](https://github.com/Qiskit/qiskit-ibm-runtime/pull/956).
See https://github.com/Qiskit/qiskit/pull/10455 for more information.
=> Move methods into class pages for docs

docs/sessions.rst
[1] links to [2] but doesn't go directly to the target section.
[1] https://qiskit.org/ecosystem/ibm-runtime/sessions.html#what-happens-when-a-session-ends
[2] https://qiskit.org/ecosystem/ibm-runtime/how_to/run_session.html#close-a-session
=> Fix link to `Close a session`

test/integration/test_account.py
`test_logging_instance_at_init` should only be tested on the quantum channel, not cloud 
Fixes #
=> Logging instance test is IQP channel only

test/unit/test_data_serialization.py
Skipping failing unit tests, they will be fixed by https://github.com/Qiskit/qiskit-ibm-provider/pull/736 which can't be merged until qiskit is updated on the server side. 
Fixes #
=> Skip unit tests until provider/736 is merged 

qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/de-warning-6cf474f11578339c.yaml
=> Add warning if DE env is used 

qiskit_ibm_runtime/ibm_backend.py, qiskit_ibm_runtime/runtime_job.py, qiskit_ibm_runtime/utils/utils.py, releasenotes/notes/no_cached_results-54d063390b9b0ae6.yaml, test/integration/test_ibm_job.py, test/integration/test_ibm_job_attributes.py
Removed the `RuntimeJob._results` member, and don't store the results every time they are retrieved. Instead, retrieve the results from the server every time.
Also fixed several related tests.
Noticed `job_tags` was not passed as a parameter when creating a new `RuntimeJob`, so added it.
Fixes #1159
=> Remove caching of results in RuntimeJob

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/channel-strategy-instance-validate-639b18b8c5d44678.yaml
If `q-ctrl` is passed in as the channel_strategy but the instance does not have it enabled, the following error will be raised: 
```
IBMNotAuthorizedError: 'This account is not authorized to use ``q-ctrl`` as a channel strategy.'
```
Fixes #1176
=> Add channel strategy instance validation

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/sampler.py, releasenotes/notes/remove-circuit-indicies-e8af9da213e463e9.yaml
This was reverted in https://github.com/Qiskit/qiskit-ibm-runtime/pull/999 but is now needed for q-ctrl. 
These inputs are no longer passed in on the server side pending `qiskit-ibm-primitives/134`
Fixes #
=> Remove circuit & observable indices run inputs

test/integration/test_fake_backends.py, test/unit/fake_provider/test_fake_backends.py
This PR cleans up the fake provider integration tests, separating the tests that concern qiskit classes (namely `BackendV2Converter`) from those that test the fake provider and backends. The qiskit tests should have remained in qiskit, but were ported because of an oversight. Additionally, it removes the use of `execute`, as this function will be deprecated (removed in 1.0), and is not necessary for these tests.
The PR also modifies the base class of the unit test to `IBMTestCase` for consistency.
Fixes https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/6894071691/job/18755457712#step:5:2779, as the`BackendV2Converter` tests were not compatible with the new release of Aer (currently being fixed in https://github.com/Qiskit/qiskit/pull/11172).
=> Fix fake backends integration test

qiskit_ibm_runtime/session.py, releasenotes/notes/revert-from-id-9b87ea2d948251d6.yaml, test/integration/test_session.py
This reverts commit 8fa0472e15ea36341acd6de67efa54a9815354e8. But keeps the `backend` parameter deprecation 
Fixes #1228
=> Revert `Session.from_id 0.15.0` changes  

qiskit_ibm_runtime/options/options.py, qiskit_ibm_runtime/qiskit_runtime_service.py, qiskit_ibm_runtime/session.py
Fixes https://github.com/Qiskit/qiskit-ibm-runtime/issues/1235
=> Stop referring to qiskit.org in API docs

qiskit_ibm_runtime/utils/backend_converter.py, releasenotes/notes/faulity-qubits-name-error-f03b90f21cd2d9bf.yaml
=> Fix backend_converter `faulty_qubit` name error

test/integration/test_backend.py
Cloud channel does not have hgps
Fixes #
=> Make `test_backend_wrong_instance` IQP only 

.github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md
With the unification of the qiskit-ibm-runtime docs and IBM Quantum Platform docs, we want to make it clear where to open an issue, depending on what page you're on when you identify a problem/suggestion to report.
Issues about documentation in the Start, Build, Transpile, Verify, Run, or Migration guides sections should be opened here: https://github.com/Qiskit/documentation/issues/new/choose
=> Add pointer to qiskit/documentation issues

qiskit_ibm_runtime/session.py, releasenotes/notes/new-session-details-field-48311b4d3313ad94.yaml
=> Add `activated_at` field to session.details()

qiskit_ibm_runtime/__init__.py
=> Replace programs with primitives in api docs 

qiskit_ibm_runtime/qiskit_runtime_service.py, releasenotes/notes/deprecate-service-runtime-1138cb5ec43fc4ff.yaml
`service.runtime` was added in #419, and is no longer necessary. 
Fixes part of #1276
=> Deprecate service.runtime

qiskit_ibm_runtime/ibm_backend.py, releasenotes/notes/max_session_time-0bd8665656bf439c.yaml, test/unit/test_session.py
Add max_time parameter to IBMBackend.open_session(). This parameter is already supported in `qiskit_ibm_provider`.
Fixes #1198
=> Add max_time parameter to IBMBackend.open_session()

docs/conf.py, requirements-dev.txt
Updates the sphinx documentation build to use KaTeX instead of MathJax because the final docs build uses KaTeX. The same change was made in Qiskit in https://github.com/Qiskit/qiskit/pull/11435.
=> switch docs from mathjax to katex

CONTRIBUTING.md, README.md, docs/tutorials/how-to-getting-started-with-sampler.ipynb, setup.py
=> Remove remaining qiskit.org links

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/runtime_job.py, releasenotes/notes/exclude-job-params-default-00133498a5c5c15d.yaml, test/integration/test_retrieve_job.py, test/unit/mock/fake_runtime_client.py
Job params should only be returned by the api with `job.inputs()`
Fixes #1307
=> Exclude params on job retrieval by default

docs/conf.py
We got source links working in API docs on docs.quantum.ibm.com! See https://github.com/Qiskit/documentation/pull/620. To do this, we need to active `sphinx.ext.viewcode`.
Note that we still plan to improve this implementation in the future to have more precise links by using `sphinx.ext.linkcode`, tracked by https://github.com/Qiskit/documentation/issues/517. This PR is to unblock the first iteration of this source links mechanism.
=> Reactive the viewcode extension for docs

docs/conf.py
We got source links working in API docs on docs.quantum.ibm.com! See https://github.com/Qiskit/documentation/pull/620. To do this, we need to active `sphinx.ext.viewcode`.
Note that we still plan to improve this implementation in the future to have more precise links by using `sphinx.ext.linkcode`, tracked by https://github.com/Qiskit/documentation/issues/517. This PR is to unblock the first iteration of this source links mechanism.
=> Reactive the viewcode extension for docs (Cherry-pick of #1312)

.github/workflows/ci.yml, .github/workflows/e2e-tests.yml, .github/workflows/integration-tests.yml, .github/workflows/q-ctrl-tests.yml, .github/workflows/unit-tests-terra-main.yml
Calling `pip install` multiple times can (deeply unfortunately) allow an environment to become out-of-sync; `pip` doesn't "remember" the constraints of previous installation commands.
One of the largest effects here is that doing `pip install -e .` _followed_ by `pip install git+<qiskit>@main` installs `qiskit-terra` from the initial installation (via `qiskit==0.45.2`), then installs `qiskit==1.0.0.dev0` from Git, which is an incompatible environment. Doing the whole environment resolution in a single `pip install` command fixes this, as the `qiskit` dependency is correctly resolved to be _only_ the `1.0.0.dev0` version.
See Qiskit/qiskit-ibm-provider#798 for the same PR over there.
=> Fix pip environment resolution

qiskit_ibm_runtime/ibm_backend.py
This is being removed from Qiskit 1.0, and the IBM Provider is (until deprecated) taking over brokering the IBM-Runtime-internal events.
See Qiskit/qiskit-ibm-provider#799 for the base, though this PR should apply cleanly even before that one, because of the backwards-compatibilty check.
=> Use IBM-Provider-vendored pub/sub mechanism

qiskit_ibm_runtime/options/options.py, test/unit/test_ibm_primitives_v2.py, test/unit/test_options.py
Remove `_experimental` flag since we now use `version`.
Fixes #
=> Remove _experimental flag

test/unit/transpiler/__init__.py, test/unit/transpiler/passes/__init__.py, test/unit/transpiler/passes/basis/__init__.py, test/unit/transpiler/passes/basis/test_convert_id_to_delay.py, test/unit/transpiler/passes/scheduling/__init__.py, test/unit/transpiler/passes/scheduling/control_flow_test_case.py, test/unit/transpiler/passes/scheduling/test_dynamical_decoupling.py, test/unit/transpiler/passes/scheduling/test_scheduler.py, test/unit/transpiler/passes/scheduling/test_utils.py
Copied from qiskit-ibm-provider
Fixes #1322
=> Add transpiler tests

docs/apidocs/fake_provider.rst, docs/apidocs/ibm-runtime.rst, docs/apidocs/transpiler.rst, docs/conf.py, qiskit_ibm_runtime/fake_provider/__init__.py
The documentation from the `transpile` and `fake_provider` modules does not appear in the rendered docs in qiskit.org/documentation or docs.quantum-computing.ibm.com.
Fixes [Qiskit Docs Issue #238](https://github.com/Qiskit/documentation/issues/238)
Replaces PR #1330.
Transpiler Doc files added:
- qiskit_ibm_runtime.transpiler.passes.html
- qiskit_ibm_provider.transpiler.passes.basis.html
- qiskit_ibm_provider.transpiler.passes.scheduling.ALAPScheduleAnalysis.html
- qiskit_ibm_provider.transpiler.passes.scheduling.ASAPScheduleAnalysis.html
- qiskit_ibm_provider.transpiler.passes.scheduling.BlockBasePadder.html
- qiskit_ibm_provider.transpiler.passes.scheduling.DynamicCircuitInstructionDurations.html
- qiskit_ibm_provider.transpiler.passes.scheduling.html
- …
=> Add missing API Refs to docs (Cherry-pick of #1343)

qiskit_ibm_runtime/utils/json.py
This commit sets the use_symengine flag during qpy export used during job payload generation if symengine is installed. For qiskit <1.0 symengine is a hard dependency on platforms that have support for it (x86_64, aarch64, and ppc64le linux and macOS) and an optional requirement on other qiskit supported platforms, and when available it greatly improves the runtime performance of symbolic expressions in Qiskit. By default QPY opts for the more compatible sympy representation of an unbound ParameterExpression as it's maximally compatible, and means that no matter the environment the payload will be loaded from it will be able to parse the payload. In QPY version 10 a new flag was added to the payload definition that enables users to use a native binary symengine representation of a …
=> Set use_symengine on qpy generation if symengine is installed

test/qctrl/__init__.py, test/qctrl/test_qctrl.py, test/unit/fake_provider/__init__.py, test/unit/fake_provider/test_fake_backends.py, test/unit/transpiler/passes/scheduling/test_utils.py
Fix a couple of import on unit tests
=> Fix for unit tests

test/integration/test_ibm_job.py, test/integration/test_results.py, test/integration/test_retrieve_job.py
More details in the issue, `test_jobs_filter_by_date` and `test_retrieve_jobs_order` fail intermittently because too many jobs are being run in parallel 
Fixes #1320
=> Update flaky integration tests

qiskit_ibm_runtime/transpiler/__init__.py, qiskit_ibm_runtime/transpiler/passes/__init__.py, qiskit_ibm_runtime/transpiler/passes/basis/__init__.py, qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py
This resulted in the imports being called `qiskit_ibm_provider` rather than `qiskit_ibm_runtime`.
=> Fix bad Sphinx API doc Provider naming (Cherry-pick of #1360)

requirements-dev.txt
`mthree` dependency is still install qiskit-terra in our CI, failing the tests 
https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/7751612975/job/21139794481
Fixes #
=> Remove mthree from requirements-dev

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/options/estimator_options.py, qiskit_ibm_runtime/options/options.py, qiskit_ibm_runtime/options/sampler_options.py, qiskit_ibm_runtime/options/transpilation_options.py, test/unit/mock/fake_runtime_client.py, test/unit/test_estimator.py, test/unit/test_estimator_options.py, test/unit/test_ibm_primitives_v2.py, test/unit/test_options.py
- Remove `initial_layout` etc from transpilation options for v2 primitives. This closes #1333 
- Move `optimization_level` into transpilation now that we only do light transpilation and don't insert DD by default anymore
- Set max optimization level to 1
- Set max resilience level to 2
Fixes #
=> Update v2 transpilation options

.github/workflows/integration-tests-qiskit-main.yml
=> Fix qiskit main integration tests cron job

qiskit_ibm_runtime/utils/json.py
This commit works around a bug in Qiskit 0.45.x, 0.46.0, and 1.0.0rc1 with the `use_symengine` flag on `qpy.dump()`. The dump function has a bug when it receives a truthy value instead of a bool literal that it will generate a corrupt qpy because of a mismatch between how the encoding was processed (the encoding is incorrectly set to sympy in the file header but uses symengine encoding in the actual body of the circuit.  This is being fixed in Qiskit/qiskit#11730 for 1.0.0, and will be backported to 0.46.1. But to ensure compatibility with 0.45.x, 0.46.0, and 1.0.0rc1 while waiting for those releases we can workaround this by just casting the value to a boolean.
=> Cast use_symengine input to a bool

qiskit_ibm_runtime/options/estimator_options.py
The error message in `_validate_resilience_level` says `optimization_level` when it should be `resilience_level`.
=> Fix the name of the attribute used in the error message

qiskit_ibm_runtime/options/utils.py, test/unit/test_ibm_primitives_v2.py
It was reported that using the `experimental` to pass in nested options didn't always work. For example:
```
options = {
"optimization_level": 0,
"execution": {
"shots": 1,
"max_circuits": 40,
},
"twirling": {"strategy": "active-circuit", "gates": True, "measure": True},
}
Estimator(backend).run([(circuit, observable, parameter_values)]).result()
```
fails with 
`main() got an unexpected keyword argument 'max_circuits'`
It turns out this could happen if the dictionary containing the experimental option (in this case `execution`) is the last one to be merged in, because in `_update_options`, the `matched` dictionary is not cleared after each iteration and the residual value can be reused. 
Fixes #
=> Fix merging experimental options

qiskit_ibm_runtime/base_primitive.py, qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/sampler.py
The `options` property was declared in the base primitive class and returned the generic `BaseOptions`. This breaks auto-complete as it only covered fields in `BaseOptions` (which has nothing). 
This PR updates the return type to be the one used by sampler or estimator. 
Fixes #
=> Fix options auto complete

qiskit_ibm_runtime/utils/json.py
Avoid converting observables to numpy arrays because https://github.com/Qiskit/qiskit-ibm-runtime/issues/1354 hasn't been fixed yet.
Using `.tolist` as a temporary replacement.
=> Convert the observables to a list when encoding

qiskit_ibm_runtime/ibm_backend.py, qiskit_ibm_runtime/provider_session.py, releasenotes/notes/sessions-endpoint-e617b028fe4a68c4.yaml, test/integration/test_session.py
The same needs to be done in `qiskit-ibm-provider` https://github.com/Qiskit/qiskit-ibm-provider/pull/817
Fixes #
=> Use POST /sessions in backend.run sessions

qiskit_ibm_runtime/base_primitive.py, qiskit_ibm_runtime/session.py, releasenotes/notes/require-cloud-backend-38a74144347c735d.yaml, test/unit/test_session.py
=> Add warning if no backend provided on cloud channel

docs/release_notes.rst
Even though we had the release note files, Reno was not including them.
=> Fix missing releases notes before Runtime 0.9

docs/release_notes.rst
Even though we had the release note files, Reno was not including them.
=> Fix missing releases notes before Runtime 0.9 (cherry-pick of #1434)

qiskit_ibm_runtime/transpiler/passes/scheduling/utils.py
Removes patch added in https://github.com/Qiskit/qiskit-ibm-runtime/pull/1383 - this was originally added as a hacky way to support both qiskit 0.45 and 1.0 
Fixes #
=> Remove `DynamicCircuitInstructionDurations` patch added in 0.19

qiskit_ibm_runtime/__init__.py
Right now, users can't import `qiskit_ibm_runtime.SamplerV1` and `qiskit_ibm_runtime.EstimatorV1` because we only expose the aliases `Sampler` and `Estimator`. That gets in the way of users being explicit about which primitive version they're using.
This also is resulting in the API docs not including the pages for both the V1 and V2 primitives in https://github.com/Qiskit/documentation/pull/973 because we didn't tell autosummary about them.
=> Allow importing SamplerV1 and EstimatorV1

qiskit_ibm_runtime/__init__.py
Right now, users can't import `qiskit_ibm_runtime.SamplerV1` and `qiskit_ibm_runtime.EstimatorV1` because we only expose the aliases `Sampler` and `Estimator`. That gets in the way of users being explicit about which primitive version they're using.
This also is resulting in the API docs not including the pages for both the V1 and V2 primitives in https://github.com/Qiskit/documentation/pull/973 because we didn't tell autosummary about them.
=> Allow importing SamplerV1 and EstimatorV1 (Cherry-pick of #1477)

docs/release_notes.rst
Reno stopped including 0.16+ and newer on the stable/0.21 branch and on main, but it still works for stable/0.20. @arnaucasau and I spent two hours trying to debug this and couldn't figure it out.
To unblock getting out release notes for 0.21, we're going to use this hacky workaround to generate two separate release notes. The API generation script in qiskit/documentation will merge back to a single list.
We're going to either investigate more closely what happened later, or switch away from Reno so it doesn't matter. See https://github.com/Qiskit/documentation/issues/978
=> Hacky fix for Reno removing 0.16+ release notes

test/integration/test_fake_backends.py
Fix for the failing fake backend tests is now in qiskit 1.0.2 
Fixes #1453
=> Re-enable fake backend tests

qiskit_ibm_runtime/ibm_backend.py
Backport of https://github.com/Qiskit/qiskit-ibm-runtime/commit/1e89d950146c7c457b4f37699bbaf53f7f709baa to the `stable/0.21` branch
=> Fix IBMBackend sphinx (#1510)

qiskit_ibm_runtime/qiskit/__init__.py, qiskit_ibm_runtime/qiskit/primitives/__init__.py, qiskit_ibm_runtime/qiskit/primitives/backend_estimator_v2.py, qiskit_ibm_runtime/qiskit/primitives/backend_sampler_v2.py, test/unit/qiskit/__init__.py, test/unit/qiskit/test_backend_estimator_v2.py, test/unit/qiskit/test_backend_sampler_v2.py
Port `BackendEstimatorV2` and `BackendSamplerV2` from Qiskit, since they are needed for local testing mode before Qiskit 1.1 release. 
Fixes #
=> Port backend primitives v2

qiskit_ibm_runtime/__init__.py, qiskit_ibm_runtime/base_primitive.py, qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/fake_provider/local_service.py, qiskit_ibm_runtime/options/utils.py, qiskit_ibm_runtime/sampler.py, qiskit_ibm_runtime/utils/utils.py, test/unit/test_estimator.py, test/unit/test_ibm_primitives_v2.py, test/unit/test_local_mode.py, test/utils.py
Add local testing mode support for V2 primitives (similar to #1495). 
If an unsupported option is passed to a V2 primitive, a warning is issued. This was not done for V1 because V1 hard codes defaults, so there was no way to differentiate user-set vs defaulted to values. V2 clears out all unset options prior to calling the service. 
There is also no release note because the one from #1495 is generic enough to cover both.
=> Local testing mode support for V2 primitivse

qiskit_ibm_runtime/options/options.py, release-notes/unreleased/1541.bug.rst, test/unit/test_estimator_options.py, test/unit/test_sampler_options.py
This is a copy of #1541 but with tests. I opened this as a separate PR because I couldn't push to @t-imamichi's repo. 
Fixes #
=> Treat resilience_level=0 for EstimatorV2 properly (replace of 1541)

qiskit_ibm_runtime/qiskit_runtime_service.py
=> Remove runtime property

docs/Makefile, release-notes/0.1.0.rst, release-notes/0.1.0rc1.rst, release-notes/0.1.0rc2.rst, release-notes/0.11.0.rst, release-notes/0.11.1.rst, release-notes/0.11.2.rst, release-notes/0.11.3.rst, release-notes/0.12.0.rst, release-notes/0.12.1.rst, release-notes/0.13.0.rst, release-notes/0.14.0.rst, release-notes/0.15.0.rst, release-notes/0.15.1.rst, release-notes/0.17.0.rst, release-notes/0.18.0.rst, release-notes/0.2.0.rst, release-notes/0.20.0.rst, release-notes/0.4.0.rst, release-notes/0.5.0.rst, release-notes/0.6.0.rst, release-notes/0.7.0.rst, release-notes/0.7.0rc1.rst, release-notes/0.7.0rc2.rst, release-notes/0.8.0.rst, release-notes/0.9.0.rst, release-notes/0.9.1.rst, release-notes/0.9.2.rst, release-notes/0.9.3.rst, release-notes/0.9.4.rst
This PR fixes how some links render after changing to Towncrier. The links that were rendered strangely were inside code blocks. We could fix this with a more complex logic of the release notes and the `conf.py`, but instead, this PR removes the code block and leaves the links as text to make them accessible again.
This change will need to be backported to stable branches
Closes https://github.com/Qiskit/documentation/issues/1070
=> Fix render of IBM links in the release notes

qiskit_ibm_runtime/qiskit/primitives/backend_sampler_v2.py, test/unit/qiskit/test_backend_sampler_v2.py
This is a port of https://github.com/Qiskit/qiskit/pull/12055 to this repository, since the current repository has its own fork of `BackendSamplerV2` until Qiskit 1.1 is released (#1523).
I would appreciate if this fix could be backported to the stable branch as well.
=> Fix `BackendSamplerV2` when used with an empty classical register

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/sampler.py, qiskit_ibm_runtime/utils/qctrl.py, release-notes/unreleased/1550.feat.rst, releasenotes/notes/q-ctrl-validation-primitives-v2-71c103cac4635a94.yaml, test/unit/test_ibm_primitives_v2.py
- This PR introduces changes to validate inputs for qctrl's primitives v2.
- Relies on the channel_strategy property
- Routes parameter validation in Primitives v2 to qctrl's logic if the q-ctrl string is found in the `channel_strategy` property
- Implements parameter validation for options in Primitives v2
=> feat: Add qctrl validation for Primitives v2

qiskit_ibm_runtime/options/pec_options.py
The current description and validation of the `PecOption.noise_gain` option is incorrect.
Values of 0 should be allowed, and correspond to full PEC mitigation of the learned noise model.
A Value of 1 corresponds to no mitigation (ie running the circuit with its native noise model)
=> Fix incorrect specification of noise_gain option

qiskit_ibm_runtime/transpiler/passes/scheduling/block_base_padder.py, qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py, qiskit_ibm_runtime/transpiler/passes/scheduling/pad_delay.py, qiskit_ibm_runtime/transpiler/passes/scheduling/scheduler.py, qiskit_ibm_runtime/transpiler/passes/scheduling/utils.py, release-notes/unreleased/1531.feat.rst, test/unit/transpiler/passes/scheduling/test_dynamical_decoupling.py
This PR partially addresses the issue (#1531) found while profiling the DD passes used for dynamic circuits, namely that `block_order_op_nodes` is very slow for common families of circuits. The changes here expose an argument
```python
block_ordering_callable: Optional[BlockOrderingCallableType] = None
```
where
```python
BlockOrderingCallableType = Callable[DAGCircuit, Generator[DAGOpNode, None, None]]
```
in the relevant places to allow the user to construct blocks using an algorithm of their choosing. No assumptions or checks are made on the validity of the output that the `block_ordering_callable` produces. This argument is propagated to
- `BlockBasePadder`
- `PadDynamicalDecoupling`
- `PadDelay`
- `BaseDynamicCircuitAnalysis`
i.e. anywhere `block_order_op_nodes` is currently used. …
=> Allow user-specified function for producing a block ordering

qiskit_ibm_runtime/estimator.py
Fix wording in error raised when using a simulator, pec_mitigation is enabled but a coupling map has not been provided.
Fixes #
=> Fix wording in error raised when validating options

qiskit_ibm_runtime/options/options.py
This PR modifies the existing `_repr_html_` method on the options base class to support recursive nesting.
Previously, it would stop expanding sub options past the first level.
Previously, I would get this for the estimator V2 options:
With this PR I get:
Sampler V2 demo:
V1 demo:
=> Add recursive nesting to HTML option table rendering

qiskit_ibm_runtime/options/zne_options.py, test/unit/test_estimator_options.py
This PR fixes some error in the way ZNE options are validated and tested.
Currently, ZNE validation and testing have the following problems:
1. The `_validate_zne_noise_factors` method passes in the case the noise factors are the empty list `[]` although this is an invalid input, since the initial check `if self.extrapolator and self.noise_factors` considers `self.noise_factors` to be `False` in case it is an empty list.
2. ZNE tests pass for wrong reason. e.g. for `{"resilience": {"zne": {"noise_factors": [1]}}}` the `test_bad_inputs` test succeeds because `ValidationError` is thrown even though the intended error (not enough noise factors) is not tested, since this error is masked by the error of not having `zne_mitigation: True` in the resilience dictionary.
These problems are handled …
=> ZNE options validation fix

qiskit_ibm_runtime/options/sampler_execution_options.py, qiskit_ibm_runtime/options/sampler_options.py, test/unit/test_sampler.py, test/unit/test_sampler_options.py
This PR adds support for level 1 measurement options in `SamplerV2`
This PR extends `ExecutionOptionsV2` to a new class, `SamplerExecutionOptionsV2` having an additional field `meas_type` which can accept the values `"classified", "kerneled", "avg_kerneled"`, where "classified" represents the usual measurement level 2 output, and the other options represent measurement level 1 output.
Fixes part of #1554
=> Level 1 measurement support in Sampler options

qiskit_ibm_runtime/base_primitive.py
=> Deprecate V1 primitives

test/unit/qiskit/test_backend_estimator_v2.py
The tests of BackendEsimatorV2 are missing a random seed for np.random (Qiskit version has).
I copied some lines from Qiskit.
=> Fix a random seed of tests for BackendEstimatorV2

qiskit_ibm_runtime/utils/utils.py
In this [comment](https://github.com/Qiskit/qiskit-ibm-runtime/pull/1593#discussion_r1565754105), I recommended changing `are_circuits_dynamic()` behavior to return False if the input circuit is a string, so it doesn't block static circuits in QASM format. However, that would cause the existing `backend.run` to call `circuit-runner` instead of `qasm3-runner` if the input is QASM. I'm not sure that's supported by `circuit-runner`, but it's best not to make the change. 
Fixes #
=> Update are_circuits_dynamic behavior

qiskit_ibm_runtime/options/__init__.py
The PR removes one link from `qiskit_ibm_runtime/options/__init__.py` that was pointing to itself. The link had a strange behavior when used in historical versions.
The PR will need backport to `stable/0.23`.
=> Remove reference to the same file in `options/__init__.py`

qiskit_ibm_runtime/options/resilience_options.py, test/unit/test_estimator_options.py
Fixes a bug in `ResilienceOptionsV2` where validation misses a corner case where `pec_mitigation` is `False` although pec options were passed.
The bug results from the check `any(asdict(self.pec).values())` which attempts to deduce whether any pec options were passed. Since some valid options are treated as `False` by Python, this check might fail. An example was added to the unit tests:
`{"resilience": {"pec": {"max_overhead": None, "noise_gain": 0}}},`
Where both the `None` and the `0` values are valid options (requiring `pec_mitigation=True`) but both are treated as `False` by Python.
The simple solution is to explicitly compare the values to `Unset` and the check passes in there is any value different than `Unset`.
The same fix was performed for `zne` and `measure_noise_learning` …
=> Small bugfix in resilience validation

qiskit_ibm_runtime/qiskit_runtime_service.py, release-notes/unreleased/1147.deprecation.rst
=> Make `name` a required param in backend()

docs/_templates/autosummary/module.rst, docs/apidocs/transpiler.rst, qiskit_ibm_runtime/options/__init__.py, qiskit_ibm_runtime/transpiler/__init__.py, qiskit_ibm_runtime/transpiler/passes/__init__.py, qiskit_ibm_runtime/transpiler/passes/basis/__init__.py, qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py, qiskit_ibm_runtime/utils/__init__.py
Closes https://github.com/Qiskit/documentation/issues/1240 and partially addresses https://github.com/Qiskit/documentation/issues/942 for runtime.
Before:
| module | status |
| --- | --- |
| qiskit.transpiler | only links to `passes` |
| qiskit.transpiler.passes | only links to `basis` and `scheduling` |
| qiskit.transpiler.passes.basis | empty, should link to ConvertIdToDelay but doesn't |
| qiskit.transpiler.passes.scheduling | useful |
Now:
| module | status |
| --- | --- |
| qiskit.transpiler.passes | links to `ConvertIdToDelay` and `scheduling` |
| qiskit.transpiler.passes.scheduling | useful |
This saves the user clicks. Now each page is useful enough to stand on its own.
This is what the index page now looks like:
This change assumes that we will not add new modules to …
=> Reorganize transpiler modules in API docs

docs/apidocs/transpiler.rst, qiskit_ibm_runtime/options/__init__.py, qiskit_ibm_runtime/transpiler/__init__.py, qiskit_ibm_runtime/transpiler/passes/__init__.py, qiskit_ibm_runtime/transpiler/passes/basis/__init__.py, qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py, qiskit_ibm_runtime/utils/__init__.py
Closes https://github.com/Qiskit/documentation/issues/1240 and partially addresses https://github.com/Qiskit/documentation/issues/942 for runtime.
Before:
| module | status |
| --- | --- |
| qiskit.transpiler | only links to `passes` |
| qiskit.transpiler.passes | only links to `basis` and `scheduling` | | qiskit.transpiler.passes.basis | empty, should link to ConvertIdToDelay but doesn't | | qiskit.transpiler.passes.scheduling | useful |
Now:
| module | status |
| --- | --- |
| qiskit.transpiler.passes | links to `ConvertIdToDelay` and `scheduling` | | qiskit.transpiler.passes.scheduling | useful |
This saves the user clicks. Now each page is useful enough to stand on its own.
This is what the index page now looks like:
This change assumes that we will not add new modules to …
=> Reorganize transpiler modules in API docs (cherry-pick of #1645)

qiskit_ibm_runtime/session.py, test/unit/test_batch.py, test/unit/test_session.py
I think it might be a good idea to also raise an `IBMRuntimeError` when a session is no longer active (or maybe at least a `QiskitError`?) in order to be able to distinguish an error related to Qiskit from any potential error happening somewhere else so you can take appropriate action such as renewing the session or saving the progress so far.
=> Raise IBMRuntimeError when session is closed

release-notes/0.14.0.rst
The docs and name recently changed from Quantum Serverless to Qiskit Serverless.
=> Fix URL for Qiskit Serverless

test/integration/test_sampler_v2.py, test/unit/qiskit/test_backend_sampler_v2.py
This PR updates tests to stop assuming that `DataBin`s are dataclasses. This fact is an internal implementation detail, and will no longer be true in qiskit 1.1.
Notice that this PR uses the private `_FIELDS` attribute. This is because there is currently no better way to do this in `qiskit<1.1,>=1.0`, so that this field has become de-facto public. Once we depend on qiskit 1.1, we can change all such instances to use the new `__len__` method. There are more methods to fix other shortcomings, as well.
Fixes #1665
=> Update tests to not assume DataBins are dataclasses

qiskit_ibm_runtime/options/zne_options.py, release-notes/unreleased/1679.feat.rst, test/integration/test_estimator_v2.py
This PR adds the `ZneOptions` attribute `amplifier` which can be one of these strings:
* `"gate_folding"` (default) uses 2-qubit gate folding to amplify noise. If the noise
factor requires amplifying only a subset of the gates, then these gates are chosen
randomly.
* `"gate_folding_front"` uses 2-qubit gate folding to amplify noise. If the noise
factor requires amplifying only a subset of the gates, then these gates are selected
from the front of the topologically ordered DAG circuit.
* `"gate_folding_back"` uses 2-qubit gate folding to amplify noise. If the noise
factor requires amplifying only a subset of the gates, then these gates are selected
from the back of the topologically ordered DAG circuit.
Fixes #1670
=> Add `resilience.zne.amplifier` to EstimatorV2 options

qiskit_ibm_runtime/utils/json.py, test/unit/test_data_serialization.py
From discussion in slack and https://github.com/Qiskit/qiskit-ibm-runtime/pull/1674, we can drop `ParameterExpression` because it's no longer an input for the primitives. 
Fixes #
=> Remove `ParameterExpression`

test/integration/test_backend.py, test/integration/test_ibm_job.py
Using a new instance for integration tests that has access to `ibmq_qasm_simulator`. The testing account has access to real backends but not the instance. 
Fixes #
=> Update integration tests to work with new test instance 

qiskit_ibm_runtime/options/twirling_options.py, release-notes/unreleased/1722.bug.rst
Fix twirling docstring to say measurement twirling is not actually enabled by default for Sampler. 
Fixes #
=> Update twirling docstring

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/qiskit_runtime_service.py, release-notes/unreleased/1732.upgrade.rst, test/unit/mock/fake_runtime_client.py, test/unit/test_backend_retrieval.py
In #1715 we implemented new pattern to retrieve backend from the service, namely, opt-int. With opt-in, the same backend can have different Target, and thus they must be different Python objects.
This PR removes backend instance cache mechanism from `QiskitRuntimeService`. Instead, cache for the configuration data is implemented in the `RuntimeClient`. `IBMBackend` object is created every time it is requested, but the source data is cached and the communication with the server occurs only once.
Once after we announce the fractional gate opt-in (not limited to fractional, some future opt-ins), user may try to compare the performance of our system with and without opt-in. One may write 
```python
backend_with_fg = service.backend("my_backend", use_fractional_gates=True)
backend_without_fg = …
```
=> Remove backend cache from QiskitRuntimeService

qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/options/estimator_options.py, release-notes/unreleased/1748.deprecation.rst, test/integration/test_estimator_v2.py, test/unit/test_estimator_options.py, test/unit/test_local_mode.py
Deprecate `optimization_level` from `EstimatorV2`. Also update the docstring as the server default is changed to 0. 
Fixes #
=> Deprecate optimization_level

qiskit_ibm_runtime/qiskit_runtime_service.py, release-notes/unreleased/1755.bug.rst
When we introduced the `use_fractional_gates` flag, we set the default to True. That'd actually break both dynamic circuits and twirling. This PR changes the default to False. 
Fixes #
=> Change use_fractional_gates default to False

setup.py
Related to #1577 - users that already have `pydantic` installed in the their environments may run into incompatibility issues because the version of `pydantic` required is not specified in `setup.py`.
Fixes #
=> Add required pydantic version in setup

.pylintrc, qiskit_ibm_runtime/fake_provider/fake_backend.py
Same fix was done long ago in https://github.com/Qiskit/qiskit-ibm-provider/pull/807 - removes the deprecation warning every time pylint is run. 
Fixes #
=> Fix pylint warning

qiskit_ibm_runtime/batch.py
The docstring of batch is incorrect. Additonaly, the example shown is trivial, as it shows how to open a batch mode to run a single circuit. This PR fixes both issues.
Fixes # 1696
=> Fixing the docstring of `Batch`

qiskit_ibm_runtime/fake_provider/fake_backend.py, qiskit_ibm_runtime/fake_provider/local_service.py, qiskit_ibm_runtime/qiskit_runtime_service.py, release-notes/0.24.1.rst, release-notes/unreleased/1764.feat.rst, test/unit/fake_provider/test_local_service.py
Add the following methods to QiskitRuntimeLocalService
backends
backend
least_busy
Fixes #1606
=> Adding backend related methods to `QiskitRuntimeLocalService`

qiskit_ibm_runtime/accounts/account.py
If users attempt to save an IQP account with just a token, and no channel specified, since the default channel is `ibm_cloud`, it will result in a missing instance error. The error message is now improved to be more clear.
Fixes #
=> Improve save_account() error msg

qiskit_ibm_runtime/fake_provider/local_service.py, release-notes/unreleased/1773.feat.rst, test/unit/test_local_mode.py
=> Support `default_shots` in EstimatorV2 local mode 

qiskit_ibm_runtime/base_runtime_job.py, release-notes/unreleased/1771.feat.rst, test/integration/test_ibm_job_attributes.py
From a slack conversation - it'd be nice if there was an easy, documented way to get the instance where a job was run. 
Fixes #
=> Add instance property to job

qiskit_ibm_runtime/runtime_job.py, qiskit_ibm_runtime/runtime_job_v2.py
Can fully remove the websocket code after the deprecation period in #1776 
Fixes #1775
=> Use polling for job status instead of websockets

qiskit_ibm_runtime/session.py, release-notes/unreleased/1780.feat.rst, test/integration/test_session.py
If the session created with `from_id` is already closed, jobs should be rejected immediately. 
Fixes #1597
=> Set _active flag to false if session already closed

qiskit_ibm_runtime/fake_provider/local_service.py
Adding on to #1764 so the following code snippet works in local mode 
```python
with Batch(backend=backend):
sampler = SamplerV2()
````
Fixes #1723
=> Add instance param to localService backend()

qiskit_ibm_runtime/ibm_backend.py, release-notes/unreleased/1791.bug.rst, test/unit/mock/fake_runtime_client.py
If `target` is called after `target_history()`, the cached backend target will be returned instead of the most current backend target. 
Fixes #1615
=> Don't cache target in target_history

qiskit_ibm_runtime/api/clients/runtime.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/qiskit_runtime_service.py, release-notes/unreleased/1794.feat.rst
=> Wait for job if maximum pending jobs limit is exceeded 

qiskit_ibm_runtime/__init__.py, qiskit_ibm_runtime/estimator.py, qiskit_ibm_runtime/fake_provider/local_service.py, qiskit_ibm_runtime/qiskit_runtime_service.py, qiskit_ibm_runtime/sampler.py, qiskit_ibm_runtime/session.py
This PR removes `RuntimeOptions` from docstrings. 
`RuntimeOptions` was the original options class used when Qiskit Runtime supported only custom programs. Now that we don't support custom programs anymore, exposing that class in the API doc would only cause confusion. Ideally we'd also clean it up from the code, but that requires a bit more work.
=> Scrub RuntimeOptions from docs

qiskit_ibm_runtime/options/__init__.py, qiskit_ibm_runtime/options/options.py
This PR breaks up the classes in `options` package into different sections, to make it easier to find:
The table for "Base primitive options" is small because the text is short. @Eric-Arellano or @beckykd, if you know to fix that please let me know.  
Fixes #
=> Break up options classes in docs

qiskit_ibm_runtime/base_runtime_job.py, qiskit_ibm_runtime/runtime_job.py, qiskit_ibm_runtime/runtime_job_v2.py, test/unit/test_circuit_runner_job.py, test/unit/test_jobs.py
From a slack conversation with @daka1510 regarding when `_download_external_result` was first added [here](https://github.com/Qiskit/qiskit-ibm-runtime/pull/709) to support osprey
> We have now cleaned up the corresponding code on the server-side to support this special result flow. Feel free to remove it from the SDK, too, if no one in this group objects.
Allowing clients to fetch data from COS directly via the SDK might become a priority again, but probably not follow this design with pre-signed URLs. Since it's all unclear right now, it's probably not a good idea to keep this code around.
Fixes #
=> Remove downloading result from external url

qiskit_ibm_runtime/utils/json.py, release-notes/unreleased/1800.bug.rst, test/integration/test_job.py
Related to #1789 and #1603 - Attempt to fix the issue where having `simplejson` installed in an environment prevents users from retrieving job results 
Fixes #
=> Fix simplejson incompatibility

qiskit_ibm_runtime/__init__.py
This results in a dedicated docs page being created like below. This is useful to avoid 404ing the page and to make extra-explicit that Estimator is now an alias for EstimatorV2.
=> Add back alias docs pages for Sampler and Estimator

release-notes/0.12.1.rst
This page was removed from current API docs, so we need to use a historical version.
=> Fix 404 link in release note

qiskit_ibm_runtime/options/zne_options.py
Zne options doc is not rendering correctly 
https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.ZneOptions
Fixes #
=> Fix zne options doc

qiskit_ibm_runtime/options/__init__.py
This PR exposes `NoiseLearnerOptions` in docs, so that they become visible in the website
=> Exposing `NoiseLearnerOptions` in docs

qiskit_ibm_runtime/options/twirling_options.py, qiskit_ibm_runtime/options/zne_options.py
We've seen many questions and confusion over `shots`, `default_shots`, and `shots_per_randomization`. This is an attempt to clarify that. 
While I'm in there, I also changed the docstring to use attributes per #1762.
Fixes #
=> Docs: clarify shots, default_shots, and twirling shots

qiskit_ibm_runtime/base_primitive.py, release-notes/unreleased/1892.deprecation.rst
=> Deprecate simulator `noise_model` option

qiskit_ibm_runtime/options/resilience_options.py
This PR improves the docstring description of `layer_noise_model` option by specifying that `NoiseLearnerResult`s are valid inputs
=> Improving docstring description of `layer_noise_model` option

qiskit_ibm_runtime/qiskit_runtime_service.py
I noticed that when decoding a V2 job, the `image` attribute is not populated. This PR is to retrieve the image and include it in the job.
=> Retrieve image info when decoding V2 jobs

qiskit_ibm_runtime/utils/json.py
Move `from_dict` import so there is no import error if `qiskit-aer` is not installed. 
Fixes #1899
=> Move from_dict import

qiskit_ibm_runtime/options/zne_options.py, release-notes/unreleased/1902.feat.rst
Closes [#1629](https://github.com/Qiskit/qiskit-ibm-runtime/issues/1629)
Tested it on a bunch of jobs, including:
- `cvbncgjkmd10008ph1z0`
- `cvbndkyvawwg0088xn30`
=> Adding `fallback` option to ZNE extrapolators

qiskit_ibm_runtime/batch.py, qiskit_ibm_runtime/session.py, release-notes/unreleased/1896.bug.rst, test/unit/test_session.py
`Session.from_id()` calls the POST /Session endpoint which is unnecessary because the session and session id already exist 
Fixes #1895
=> Don't create new session in `from_id()`

test/integration/test_noise_learner.py
Tests are failing - https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/10713618396/job/29705945019
Noise learner jobs return `RuntimeJobV2` so the status should be a string instead of the Qiskit class `JobStatus`
Fixes #
=> Update noise learner tests

qiskit_ibm_runtime/utils/json.py, qiskit_ibm_runtime/utils/noise_learner_result.py, release-notes/unreleased/1908.feat.rst, test/integration/test_noise_learner.py, test/unit/test_data_serialization.py
Allows `NoiseLearnerResult` to be JSON serialized/deserialized with the `RuntimeEncoder` and `RuntimeDecoder`.
Fixes #1908
=> Make `NoiseLearnerResult` JSON serializable

qiskit_ibm_runtime/api/client_parameters.py, qiskit_ibm_runtime/qiskit_runtime_service.py, qiskit_ibm_runtime/utils/__init__.py, qiskit_ibm_runtime/utils/utils.py, release-notes/unreleased/1914.deprecation.rst, release-notes/unreleased/1914.feat.rst, test/unit/test_client_parameters.py
The service has other environments that need to be accessible via the provider in which the url cannot be properly generated with the current code. To enable using the provider with these environments without hardcoding strategies for these edge cases, I added the option for a custom url resolver.
Use example:
```
def custom_url(url, instance, private_endpoint = False):
return "https://my-custom-url"
service=QiskitRuntimeService(channel="ibm_cloud", url="https://test.cloud.ibm.com", instance="crn:v1:my_instance", token="my_token", url_resolver=custom_url)
```
=> add custom url resolver to enable using other endpoints

qiskit_ibm_runtime/base_primitive.py, release-notes/unreleased/1922.but.rst, test/unit/test_session.py
We cannot run primitive inside session with fractional gates. This PR fixes the bug.
This is the current behavior:
```python
from qiskit_ibm_runtime import QiskitRuntimeService, Session, SamplerV2
service = QiskitRuntimeService()
backend = service.backend(use_fractional_gates=True)
with Session(backend=backend) as _:
primitive = SamplerV2()
assert primitive._backend.options.use_fractional_gates is True  # fail
```
Because of this, this session fails in running the primitives because of the ISA circuit validation. When we instantiate a primitive inside the session context, the backend is reloaded from the service attached to the session without the optin flag.
=> Fix missing fractional gates in primitive in session

docs/index.rst
This has no impact on end users, only the Sphinx docs used by qiskit-ibm-runtime devs.
Before:
After:
=> Fix missing version in home page for developer docs

qiskit_ibm_runtime/qiskit_runtime_service.py, release-notes/unreleased/1931.deprecation.rst
=> Deprecate channel strategy

qiskit_ibm_runtime/ibm_backend.py, qiskit_ibm_runtime/qiskit_runtime_service.py, release-notes/unreleased/1938.feat.rst, test/unit/test_backend_retrieval.py
Today the `use_fractional_gates` flag is used to return the backend target with fractional gates OR with control flow operations. However, there are cases when a user wants to see all the instructions a backend supports. This PR allows `use_fractional_gates=None`, which will bypass the instruction filtering. 
Fixes #1937
=> Allow retrieving a backend with no instruction filtering

qiskit_ibm_runtime/utils/noise_learner_result.py, qiskit_ibm_runtime/visualization/draw_layer_error_map.py, test/unit/test_noise_learner_result.py
A previous PR added `plotly` as an optional dependency. Yet, a few files do top-level import of `plotly`, which errors unless users have `plotly` pre-installed. This PR fixes the issue by moving `plotly` imports inside the functions that need it
=> Remove top-level plotly imports

release-notes/0.5.0.rst, release-notes/0.7.0.rst, release-notes/0.8.0.rst, release-notes/0.9.1.rst, release-notes/0.9.2.rst, release-notes/0.9.3.rst, release-notes/0.9.4.rst
These APIs were removed in Runtime 0.30, so the anchor links stopped working.
=> Fix broken anchor links in release notes

qiskit_ibm_runtime/utils/utils.py, test/unit/test_sampler.py
#1916 fixed a bug related to connectivity inside control operations. @jakelishman [has pointed out](https://github.com/Qiskit/qiskit/issues/13227#issuecomment-2377404138) a case where the fix does not apply correctly. The case is exemplified in the test `test_isa_inside_condition_block_body_in_separate_circuit`, which is added in the current PR. Running the test, either on Shrebrooke or Cusco, results with
```
qiskit_ibm_runtime/utils/utils.py:61: in _is_isa_circuit_helper
qargs = tuple(qubit_map[bit] for bit in instruction.qubits)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.0 = <tuple_iterator object at 0x7f3c30d83af0>
>   qargs = tuple(qubit_map[bit] for bit in instruction.qubits)
E   KeyError: Qubit(QuantumRegister(2, 'inner'), 0)
```
The current PR …
=> Bug fix: ISA check inside control flow operations whose body is defined in a separate circuit

tools/concat_release_notes.py
For Windows, you have to explicitly set the file encoding with `pathlib` APIs.
=> Fix concat_release_notes.py on Windows

qiskit_ibm_runtime/utils/json.py, test/unit/test_data_serialization.py
This PR adds JSON serialization support for the `DoubleSliceSpan` object added in #1982 .
I notice now that `SliceSpan` uses `"ExecutionSpan"` and `ExecutionSpans` uses `"ExecutionSpanCollection"` as the json type keys: this is a mistake, but I chose to overlook it in this PR as being out-of-scope.
=> Add serialization support for DoubleSliceSpan

qiskit_ibm_runtime/base_primitive.py, qiskit_ibm_runtime/noise_learner/noise_learner.py, release-notes/unreleased/1995.feat.rst, test/unit/test_ibm_primitives_v2.py, test/unit/test_noise_learner.py
Add a `backend()` method to the primitives + `NoiseLearner`, so users can extract the backend the primitive is configured for. 
Note that similar to `job_id`, I would have preferred it to be an attribute rather than a method. But since it's already a method in `Job`, having that consistency is better. 
Fixes #
=> Add backend method

qiskit_ibm_runtime/execution_span/__init__.py, qiskit_ibm_runtime/execution_span/double_slice_span.py, qiskit_ibm_runtime/execution_span/twirled_slice_span.py, qiskit_ibm_runtime/utils/json.py, release-notes/unreleased/2011.feat.rst, test/unit/test_data_serialization.py, test/unit/test_execution_span.py
This new `ExecutionSpan` subclass is added explicitly for the case where a sampler is called with twirling enabled. 
`SliceSpan` and `DoubleSliceSpan` are insufficient because data from twirled experiments is not contiguous in the right way to make them work, especially when batching constants don't magically align with num_randomizations.
=> Add execution_span.TwirledSliceSpan

qiskit_ibm_runtime/visualization/draw_execution_spans.py, release-notes/unreleased/2014.bug.rst
Prior to this PR, the location of hover text was off by a factor of three because they were not accounting for the fact that every plotted span essentially corresponds to three marker positions: the time start, the time stop, the None value indicating "move to the next one".
=> Fix `draw_execution_spans()` hover text placement

qiskit_ibm_runtime/utils/backend_decoder.py
Some components still (unwisely) depend on this name. This PR adds it back temporarily to give them time to switch.
Fixes #
=> Add a private alias to decode_backend_configuration()

qiskit_ibm_runtime/utils/utils.py, test/unit/test_sampler.py
The current RZZ validation fails with parameter expression as follows.
```python
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
from qiskit_ibm_runtime import QiskitRuntimeService, SamplerV2
x = Parameter("x")
qc = QuantumCircuit(2, 2)
qc.rzz(2 * x, 0, 1)
qc.measure([0, 1], [0, 1])
service = QiskitRuntimeService(instance="...")
backend = service.backend("ibm_torino", use_fractional_gates=True)
sampler = SamplerV2(backend)
_ = sampler.run([(qc, 0.1)])
```
0.33.1
```
File "/Users/ima/tasks/4_2024/qiskit/runtime/tmp/frac.py", line 14, in <module>
_ = sampler.run([(qc, 0.1)])
^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ima/envs/qiskit/lib/python3.12/site-packages/qiskit_ibm_runtime/sampler.py", line 120, in run
return …
```
=> Fix the parameter expression case for RZZ validation

qiskit_ibm_runtime/fake_provider/local_service.py, release-notes/unreleased/1990.feat.rst, test/unit/test_sampler.py
This change passes through the `simulator.noise_model` option to the `BackendSamplerV2` as a `noise_model` option of `run_options` if the primitive supports the `run_options` option (support was added in Qiskit 1.3).
Additionally, this change translates the `execution.meas_type` option into `meas_level` and `meas_return` options of `run_options` if the `BackendSamplerV2` supports `run_options`. This change allows support for level 1 data in local testing mode, where otherwise the default is only to return classified data.
=> Add support for noise model and level 1 data to local sampler

qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py
This PR updates the `PadDynamicalDecoupling` pass to work with the Qiskit 1.3 updates on the `DAGCircuit` class. In particular, before this PR, https://github.com/Qiskit/qiskit/pull/12550 would break the `test_insert_midmeas_hahn` test from `test/unit/transpiler/passes/scheduling/test_dynamical_decoupling.py`, which is now fixed.
If helpful, this PR can also be incorporated into #2041, but thought that it might make sense to separate it given that it's not only changing unit tests. In principle there should be no user-facing changes so no reno was added.
Fixes #
=> Update `PadDynamicalDecoupling` pass to conform to Qiskit 1.3 data model 

docs/conf.py, qiskit_ibm_runtime/fake_provider/__init__.py, qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py, qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py, requirements-dev.txt
This PR replaces all the `.. jupyter-execute::` calls with `.. plot::`. The change will improve the docs in different ways. For example, it will allow us to leverage the `:alt:` option of the `plot` directive to set an alt text to all the images, which wasn't possible using the `jupyter-execute` directive, and, in addition, it will prevent us from different issues when building the documentation caused by the unreliable nature of `juptyer-execute` as explained in https://github.com/Qiskit/qiskit/pull/9346
In this PR in `qiskit/documentation` we can see the git diff caused by this replacement. The change is mainly the renaming of the images because some of them now have a dedicated code block: https://github.com/Qiskit/documentation/pull/2403/files
=> Replace `jupyter-execute` with `plot` from docs

qiskit_ibm_runtime/utils/json.py, test/unit/test_data_serialization.py
This PR adds serialization support for `EstimatorPubResult` added in #1951.
=> Add serialization support for EstimatorPubResult

qiskit_ibm_runtime/runtime_options.py
Improved documentation for private option.
Fixes #
=> Improved documentation for the private option

qiskit_ibm_runtime/api/rest/base.py, qiskit_ibm_runtime/api/rest/cloud_backend.py, qiskit_ibm_runtime/api/rest/program_job.py, qiskit_ibm_runtime/api/rest/root.py, qiskit_ibm_runtime/api/rest/runtime.py, qiskit_ibm_runtime/api/rest/runtime_session.py, test/unit/test_runtime_client.py
Added `{"Content-Type": "application/json"}` and `{"Accept": "application/json"}` to the headers of the appropriate http requests. Also added `IBM-API-Version` to the header of all API requests. 
Fixes #2063 
Fixes #2064 
Also fixes `ws-primitives #220`
=> Add content/accept headers to appropriate http requests

qiskit_ibm_runtime/qiskit_runtime_service.py
=> Update docstring in jobs()

qiskit_ibm_runtime/options/estimator_options.py
Indent was causing the text to become bold.
HTML is correct now:
```
<ul class="simple">
<li>
<p>0: No mitigation.</p>
</li>
<li>
<p>
1: Minimal mitigation costs. Mitigate error
associated with readout errors.
</p>
</li>
<li>
<p>
2: Medium mitigation costs. Typically reduces bias
in estimators but is not guaranteed to be zero bias.
</p>
</li>
</ul>
```
Fixes #2115
=> Fix bold EstimatorOptions text

DEPRECATION.md
There was a question this morning on what is considered public API. This PR updates the deprecation to include that section (credit goes to the Qiskit team as it's largely copied from there). 
Fixes #
=> Update deprecation policy to include what is public

release-notes/0.20.0.rst, release-notes/0.30.0.rst
I moved around some stuff in the documentation and broke these links.
=> Update links in release notes

release-notes/0.20.0.rst
The method `open_session()` was removed in https://github.com/Qiskit/qiskit-ibm-runtime/pull/1962, and the link will break when the v0.35.0 docs are live.
=> Update broken link in the release notes

qiskit_ibm_runtime/qiskit_runtime_service.py, release-notes/unreleased/2156.bug.rst
When retrieving jobs with `service.jobs()`, there is no way to distinguish between v1 and v2 primitives. Since the v1 primitives were completely removed over 6 months ago in `0.28.0`, we should default to returning `RuntimeJobV2`.
There shouldn't be a purpose for `RuntimeJob` anymore so we can handle its deprecations and removal in a separate PR. 
Fixes #
=> Default to returning RuntimeJobv2 in jobs()

qiskit_ibm_runtime/accounts/account.py, test/decorators.py
https://github.com/Qiskit/qiskit-ibm-runtime/pull/2081 changed the IQP subdomains by removing `-computing`. This caused the test credentials to default to the `ibm_cloud` channel if the old url was used. 
Fixes #
=> Fix issues from url subdomain changes

qiskit_ibm_runtime/fake_provider/fake_backend.py, qiskit_ibm_runtime/ibm_backend.py, qiskit_ibm_runtime/models/backend_configuration.py, qiskit_ibm_runtime/models/backend_properties.py, qiskit_ibm_runtime/models/exceptions.py, qiskit_ibm_runtime/utils/backend_converter.py, qiskit_ibm_runtime/utils/options.py
https://github.com/Qiskit/qiskit/pull/13793 removes the `qobj` module. A consequence of this removal is the move of `MeasLevel` and `MeasResult` from `qiskit.qobj.utils` to `qiskit.result`. This PR allows to import from both paths for compatibility with 1.x and 2.x.
The same PR removes configuration and property errors. Because the `BackendConfiguration` and `BackendProperties` classes have been vendored in qiskit-ibm-runtime, the errors should be too.
Fixes #
This PR will allow to fix: https://github.com/Qiskit/qiskit-neko/issues/52
=> Update use of classes removed in Qiskit 2.0

qiskit_ibm_runtime/utils/backend_converter.py
Since `defaults` was removed as a parameter in #2116, we don't want `convert_to_target` to fail if defaults are still being passed in. 
Fixes #
=> Update convert_to_target to handle defaults

test/integration/test_ibm_job_attributes.py, test/integration/test_retrieve_job.py
These tests are still failing on cloud staging because the job retrieval timing is off by ~ 10 seconds
Fixes #
=> Add timing buffer for cloud job retrieval tests

qiskit_ibm_runtime/options/twirling_options.py
Small clarification for `enable_measure` to sounds less like talking about classical registers. And few `tt`s to make it easier to parse
=> Fix some formatting in twirling_options docs and clarify enable_measure a bit

qiskit_ibm_runtime/execution_span/double_slice_span.py, qiskit_ibm_runtime/execution_span/twirled_slice_span.py, release-notes/unreleased/2184.bug.rst, test/unit/test_execution_span.py
Fixes bug with `DoubleSliceSpan.mask` and `TwirledSliceSpan.mask` when their shapes are one-dimensional.
Fixes #2184
=> Fix DoubleSliceSpan and TwirledSliceSpan mask methods

qiskit_ibm_runtime/ibm_backend.py, qiskit_ibm_runtime/qiskit_runtime_service.py, release-notes/0.24.0.rst
This PR updates some links that will be broken once Qiskit 2.0 is released. 
The links were also updated in the `qiskit/documentation` repo in the following [PR](https://github.com/Qiskit/documentation/pull/2803). In that PR, the commits https://github.com/Qiskit/documentation/pull/2803/commits/ef106e009f249530f7771daa237f74c4077a5b93 and https://github.com/Qiskit/documentation/pull/2803/commits/81ea4bb005594dde41bd2aee12466b136e149a60 show all the links/pages that need to be reviewed in this repo for the versions 0.37 and 0.38 respectively. The vast majority of them are auto-generated links, and for that reason this PR is just updating a subset of them.
=> Fix future broken links in preparation for Qiskit 2.0

test/unit/test_estimator.py
A tiny PR that deletes a redundant line. The line initializes a variable, which is then redefined in the subsequent line, without being used.
=> Remove redundant line

docs/conf.py
The documentation source of truth is moving to https://quantum.cloud.ibm.com.
=> Update intersphinx mapping for Qiskit

test/integration/test_noise_learner.py
This PR fixes a test that was hard-coded to assume that noise models have an order that persists on round-trip to the estimator.
That this test passed before was based on the assumption of order preservation of noise models, which is an implementation detail.
=> Stop assuming noise model ordering persists

qiskit_ibm_runtime/qiskit_runtime_service.py
For `QiskitRuntimeService`, Sphinx uses the type hints from `__new__` instead of `__init__`. Tried configuring some of the Sphinx `conf.py` settings but nothing seemed to work. 
Fixes #2228
=> Manually add type hints for QiskitRuntimeService

qiskit_ibm_runtime/api/auth.py, test/integration/test_session.py
`test_session_from_id`: This test has been updated multiple times recently because session behavior is different on classic IQP and new IQP (https://github.com/Qiskit/qiskit-ibm-runtime/issues/2188). On the new IQP, one job has to complete first before the backend can be returned in `session.details()`. Also the session does not close right away when `close()` is called. 
After https://github.com/Qiskit/qiskit-ibm-runtime/pull/2102, `test_backend_deepcopy` started failing because of the use of `IAMTokenManager` in the Cloud Auth init function. 
I'll test that the integration tests are passing in my fork 
Fixes #
=> Integration test updates

qiskit_ibm_runtime/ibm_backend.py, release-notes/unreleased/2261.bug.rst
`backend.target()` doesn't use backend defaults anymore.
Fixes #2260
=> Remove backend defaults check in target()

qiskit_ibm_runtime/options/dynamical_decoupling_options.py
* Some tt for the defaults
* The second line bullets seems to do create bolds in the first line.
=> Formatting issues in dynamical_decoupling_options.py

qiskit_ibm_runtime/utils/utils.py, release-notes/unreleased/todo.other.rst
Some users reported that the "has been provided" wording sounded like the backend was providing that angle rather than it having been included in the circuit submitted by the user so here "provided" is changed to "requested" to make it more clear that it was the user's request that led to the error.
=> Clarify rzz out of range error message

test/integration/test_job.py
This test should've been removed long ago because a backend is required. It was only passing because `service.backend(None)` will just return the first backend from the list of available backends. 
It's been failing for the past few days because the first backend selected, `ibm_quebec`, has been offline. 
Fixes #
=> Remove `test_run_program_missing_backend_ibm_cloud`

qiskit_ibm_runtime/accounts/management.py
Reported from slack - on `0.40.1`, if a user does not have any accounts with `ibm_quantum_platform` as the channel name saved and then tries QiskitRuntimeService(channel="ibm_quantum_platform"), the service will look for any default accounts saved instead. If an IQP classic account exists (`default-ibm-quantum`), then it will be selected and there will be a misleading error message. This is fixed on the main branch because of the IQP removal PR. 
Now (on the main branch), if saved accounts with `ibm_quantum_platform` don't exist, the service will check for the default `ibm_cloud` account which would still work. We should still update the error message in the `_discover_account()` method to be more helpful. 
@ElePT Let me know if I captured everything correctly here.
Fixes #
=> Update error message if no saved accounts are found

qiskit_ibm_runtime/accounts/management.py, test/unit/test_account.py
Reported in slack - if a user has `ibm_quantum` channel accounts saved then calling `saved_accounts()` will result in an error because the legacy account can not be initialized (only a bug on main, not `0.40.1`). 
Fixes #
=> Allow `saved_accounts()` to return even if legacy accounts are saved

qiskit_ibm_runtime/options/zne_options.py
Fixing the `zne_options` docstrings. I'm not sure what happened with the math formatting because we added the extra `\` in https://github.com/Qiskit/qiskit-ibm-runtime/pull/2061 but now it appears incorrect again. 
Fixes #2371
=> Fix zne_options Extrapolator docstring

qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py
This PR fixes a link to the classical-feedforward-and-control-flow guide in the documentation. We want to intentionally leave off the locale to make sure the users will go the language they selected. The platform uses cookies to determine what language to use when it's not specified in the URL.
This was caught by [CI](https://github.com/Qiskit/documentation/actions/runs/17791834953/job/50570458896?pr=3925#step:5:18) in Qiskit/documentation.
=> Fix link to the documentation

qiskit_ibm_runtime/qiskit_runtime_service.py, test/unit/test_backend_retrieval.py, test/unit/test_job_retrieval.py, test/unit/test_session.py
I just noticed that the warnings we added in #2375 are triggered by `jobs()` and `job()` and I don't think we want that. We don't need to show the list of instances used in a warning message when retrieving jobs. 
Fixes #
=> Job methods should not trigger new instance warnings

CONTRIBUTING.md, docs/conf.py, qiskit_ibm_runtime/models/backend_configuration.py, release-notes/unreleased.rst, release-notes/unreleased/2386.update.rst, test/integration/test_backend_serialization.py, test/integration/test_fake_backends.py, tools/verify_headers.py, tools/verify_images.py
- Fixes Issue #2386 
- An inconsistency in `rep_times` due to lack of unit conversion in `to_dict()` function in `QasmBackendConfiguration` has been fixed by adding the conversion ([commit](https://github.com/Qiskit/qiskit-ibm-runtime/commit/d42379e1ad2bad2e25e9f74970a1d445ce7c9f45)).
Tests added:
- In `test_fake_backends.py` under integration tests, added an assert line to check rep_time value consistency on roundtrip to `test_to_dict_configuration` ([commit](https://github.com/Qiskit/qiskit-ibm-runtime/commit/b7408195919e8bd54fd6033e63a7039f92e8a656)).
- Included `rep_times` for undergoing deserialization check from backend configuration data, similar to `qubit_lo_range` and `meas_lo_range` ([commit](https://github.com/Qiskit/qiskit-ibm-runtime/commit/3a0ba71966f18049c574c65e18815f1e7e5c …
=> Fixed inconsistentcy in rep_times when passed via BackendConfiguration dict conversions

release-notes/0.23.0.rst, release-notes/0.35.0.rst
As part of https://github.com/Qiskit/documentation/issues/3787, the [qiskit-runtime](https://quantum.cloud.ibm.com/docs/migration-guides/qiskit-runtime) migration guide has been archived, and this PR replaces an old link from the release notes to point to a permalink to the markdown file on GitHub.
This change will need backport to the `stable/0.42` branch.
It will be synced into Qiskit/documentation through https://github.com/Qiskit/documentation/pull/4009
=> Replace archived migration guide link from the release notes
