.github/workflows/cron-staging.yml
test/ibm/runtime/test_runtime_integration.py

Fix runtime integration tests
Fixes #

Fix runtime integration tests

---

qiskit_ibm_runtime/utils/runtime.py

Copied from https://github.com/Qiskit-Partners/qiskit-ibm/pull/205
Fixes #

Use context manager with BytesIO

---

Makefile

Remove deleted test suites from Makefile and redistribute remaining across test1, 2 and 3.
Fixes #

Remove deleted test suites from Makefile and redistribute

---

.github/ISSUE_TEMPLATE/enhancement_request.md

Add acceptance criteria section to enhancement template. For bug reports the Expected behavior can be used to define acceptance criteria.
Implementing feedback from sprint retrospective.

Add acceptance criteria section to enhancement template

---

qiskit_ibm_runtime/api/rest/cloud_backend.py
qiskit_ibm_runtime/api/rest/runtime.py

Created a REST adapter for accessing the IBM Cloud backends, backend properties, configuration, status and pulse defaults.
Fixes #

Rest adapter for IBM Cloud backends

---

tox.ini

This just adds the requirements files to your `tox` configuration - previously `tox` testing commands would fail because the internal environments wouldn't have all the necessary requirements.
none

Add requirements to tox environment dependencies

---

qiskit_ibm_runtime/runtime_program.py

Print program id in service.programs()
Fixes #

Display program id in service.programs()

---

qiskit_ibm_runtime/runtime_job.py

Print program and job id in service.jobs()

Display job and program id in service.jobs()

---

tools/deploy_documentation.sh

Fix docs upload path

---

test/integration/test_interim_results.py

Fix interim results test cases
Fixes #

Fix interim results test cases

---

qiskit_ibm_runtime/api/session.py

Retry on 521 Cloudflare web server is down
Fixes #163

Retry on 521

---

releasenotes/config.yaml

Fixes docs publish failure https://github.com/Qiskit/qiskit-ibm-runtime/runs/5364941003?check_suite_focus=true#step:5:532
Fixes #

Configure reno to use default branch as main

---

.github/workflows/deploy.yml

Allow to trigger workflow that publishes the documentation manually

---

.github/workflows/deploy.yml
.github/workflows/docs.yml

Allow docs publish manual trigger, not deploy

---

qiskit_ibm_runtime/runtime_job.py
releasenotes/notes/wait-for-final-state-bug-02ebbe8df7a252d0.yaml
test/integration/test_job.py

Cherry picked from main branch 
Hope it's ok to create a branch here - I don't think there's a way to cherry pick to `stable/0.1` from my fork 
Fixes #

Update wait for final state (#194)

---

qiskit_ibm_runtime/utils/json.py

Parameter is a sub class of ParameterExpression and that's why Parameter was getting converted to ParameterExpression.
Fixes #

Add Parameter serialization

---

qiskit_ibm_runtime/__init__.py
qiskit_ibm_runtime/ibm_sampler.py
qiskit_ibm_runtime/sampler.py
test/integration/test_ibm_sampler.py

I don't know how to serialize ParameterView, so I am not passing parameters in the tests now.
Fixes #

Integration tests for Sampler

---

qiskit_ibm_runtime/qiskit/__init__.py

Getting import error when pip installing from main.
`pip install git+https://github.com/Qiskit/qiskit-ibm-runtime.git`
Fixes #209

Fix import error

---

README.md

Fix quick start guide link

---

test/integration/test_ibm_estimator.py
test/integration/test_ibm_sampler.py

Pass backend since automatic selection is not available for legacy

---

setup.py

Bump terra version to 0.20.0

---

docs/release_notes.rst

Build release notes for 0.3.0

---

docs/release_notes.rst

Revert temp release notes change so docs build works on forks

---

qiskit_ibm_runtime/qiskit_runtime_service.py

Adding check for `ibm_quantum` since `instance` is only supported in `ibm_quantum` for filtering backends.
Fixes a couple of failing integration tests https://github.com/Qiskit/qiskit-ibm-runtime/runs/5844881493?check_suite_focus=true#step:5:1520

Fix failing integration tests

---

qiskit_ibm_runtime/runtime_session.py

Add backend to session info
Fixes #249

Add backend to session info

---

docs/release_notes.rst

Build 0.4.0 release notes

---

docs/release_notes.rst

Revert temp version info since it fails on fork doc builds

---

docs/release_notes.rst

Add temp versions for release docs

---

docs/tutorials/grover_with_sampler.ipynb
docs/tutorials/how-to-getting-started-with-estimator.ipynb
docs/tutorials/how-to-getting-started-with-sampler.ipynb
docs/tutorials/sea_with_sampler.ipynb
docs/tutorials/vqe_with_estimator.ipynb

Fix getting started links

---

docs/tutorials/how-to-getting-started-with-estimator.ipynb
docs/tutorials/how-to-getting-started-with-sampler.ipynb

Fixes bullet points are not rendered correctly in getting started guides ([sampler](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/how-to-getting-started-with-sampler.html) and [estimator](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/how-to-getting-started-with-estimator.html))
Also removed `` around `Estimator` and `Sampler` inside markdown links `\[\]\(\)`. Not sure why this is causing problem.
Fixes #293

Fix bullet points

---

docs/faqs.rst
docs/faqs/max_execution_time.rst
docs/faqs/open_source_vs_ibm_cloud_primitives.rst

Update [Frequently Asked Questions](https://qiskit.org/documentation/partners/qiskit_ibm_runtime/faqs.html) to include [what is the maximum execution time](https://github.com/Qiskit/qiskit-ibm-runtime/blob/stable/0.3/docs/max_time.rst)
Fixes #292

Add max execution time to faq

---

qiskit_ibm_runtime/accounts/exceptions.py

Make `AccountsError` a subclass of `IBMAccountError`

---

qiskit_ibm_runtime/qiskit_runtime_service.py

Add missing circuit_indices in example

---

README.md
docs/conf.py
qiskit_ibm_runtime/__init__.py
qiskit_ibm_runtime/ibm_backend.py

Qiskit Runtime IBM Quantum Client -> Qiskit Runtime IBM Client
Updating the project name for naming alignment. No impact on end user.

Project name update

---

docs/tutorials/01_introduction_ibm_cloud_runtime.ipynb
docs/tutorials/02_introduction_ibm_quantum_runtime.ipynb
docs/tutorials/05_uploading_program.ipynb
docs/tutorials/grover_with_sampler.ipynb
docs/tutorials/sample_expval_program/qiskit_runtime_expval_program.ipynb
docs/tutorials/vqe.ipynb
docs/tutorials/vqe_with_estimator.ipynb

This fixes some doc typos, including formatting typos. For instance, I've put newlines before Markdown lists so that they render properly on qiskit.org.

Fix some doc typos, including formatting typos

---

docs/getting_started.rst

Remove unused import on getting started page

---

qiskit_ibm_runtime/api/clients/runtime.py
qiskit_ibm_runtime/api/rest/runtime.py
qiskit_ibm_runtime/qiskit_runtime_service.py
releasenotes/notes/creation-date-filters-871a1ca3c0d96fda.yaml
test/integration/test_retrieve_job.py
test/program.py
test/unit/mock/fake_runtime_client.py
test/unit/test_job_retrieval.py

Filter jobs with created after/before parameters

---

qiskit_ibm_runtime/api/session.py
releasenotes/notes/not-authorized-error-31241cd68d8a26d7.yaml
test/integration/test_auth_client.py

Raise IBMNotAuthorizedError if token is incorrect 

---

qiskit_ibm_runtime/qpy/binary_io/circuits.py

Co-authored-by: Matthew Treinish <mtreinish@kortar.org>
Copy latest updates from qpy module in terra. https://github.com/Qiskit/qiskit-terra/pull/7933
Fixes #

Fix QPY deserialization of UCRX, UCRY, and UCRZ gates

---

docs/release_notes.rst

Fix release notes for 0.5.0

---

tools/deploy_documentation.sh

Fix docs deploy failure (backport #388)

---

docs/conf.py
docs/tutorials/sample_expval_program/qiskit_runtime_expval_program.ipynb
test/unit/mock/fake_account_client.py
test/unit/test_backend_retrieval.py

Terra 0.21 released earlier today - fake backends have been moved 
Fixes #

Fix fake backend imports

---

qiskit_ibm_runtime/qpy/__init__.py
qiskit_ibm_runtime/qpy/binary_io/__init__.py
qiskit_ibm_runtime/qpy/binary_io/circuits.py
qiskit_ibm_runtime/qpy/binary_io/schedules.py
qiskit_ibm_runtime/qpy/binary_io/value.py
qiskit_ibm_runtime/qpy/common.py
qiskit_ibm_runtime/qpy/formats.py
qiskit_ibm_runtime/qpy/interface.py
qiskit_ibm_runtime/qpy/type_keys.py

Copy over QPY updates from qiskit terra 0.21.0.
Fixes #

Qpy 0.21 updates

---

docs/versionutils.py

This PR is on hold until the translation team completes QA of the translated docs
Fixes #

Prepare to publish Spanish and Japanese runtime docs

---

docs/versionutils.py

* publish Spanish and Japanese runtime docs
* fix typo
(cherry picked from commit 3340ad1675923430eb2fdc73d4937576a18bc8da)
Backport #421 
Fixes #

Prepare to publish Spanish and Japanese runtime docs (#421) (backport #421)

---

docs/versionutils.py

(cherry picked from commit 6b7b35132250588b3a93bd17d19e351b6ef68f65)
Backport https://github.com/Qiskit/qiskit-ibm-runtime/pull/426
Fixes #

Fix typo (Backport #426)

---

docs/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.ipynb

to simply the output ->  to simplify the output
Fixes #

Fix a typo in runtime vqe program notebook

---

docs/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.ipynb

to simply the output ->  to simplify the output
Cherry pick #438 into main 
Fixes #

Fix typo in runtime vqe program notebook

---

docs/tutorials/vqe_with_estimator.ipynb

Qiskit Nautre -> Qiskit Nature
Fixes #

Fix typo in vqe tutorial 

---

qiskit_ibm_runtime/qpy/binary_io/schedules.py
requirements.txt
setup.py

co-authored-by: nkanazawa1989 <nkanazawa1989@gmail.com>
Copying over most recent QPY update
Fixes #

Fix qpy limit_amplitude bug 

---

qiskit_ibm_runtime/estimator.py
test/integration/test_estimator.py
test/integration/test_sampler.py

Fixes all the failing integration tests 
Related to #462

Update sampler/estimator tests 

---

qiskit_ibm_runtime/ibm_backend.py
releasenotes/notes/add-backend-run-911bda849f637ca0.yaml
test/integration/test_backend.py

```
backend = service.backend('ibmq_qasm_simulator')
backend.run(circuits = ...)
```
Fixes #459

Add backend.run()

---

qiskit_ibm_runtime/ibm_backend.py

Add kwargs to backend.run

---

qiskit_ibm_runtime/qiskit_runtime_service.py

Add deprecation warning for low usage programs 

---

docs/tutorials/how-to-getting-started-with-estimator.ipynb

an optional list -> An optional list
Fixes #

fix typo in how-to-getting-started-with-estimator.ipynb

---

qiskit_ibm_runtime/qiskit_runtime_service.py

This adds a whitespace; otherwise, I see:
```
Backend [...] cannot be found in anyhub/group/project for this account.
```

Fix missing space in exception error message

---

qiskit_ibm_runtime/estimator.py
qiskit_ibm_runtime/qiskit/primitives/base_estimator.py
qiskit_ibm_runtime/qiskit/primitives/base_sampler.py
qiskit_ibm_runtime/sampler.py

Remove `parameters` in `run` method to align with https://github.com/Qiskit/qiskit-terra/pull/8684

Remove `parameters` in `run` method

---

.github/workflows/ci.yml
qiskit_ibm_runtime/estimator.py
qiskit_ibm_runtime/qiskit/primitives/utils.py
qiskit_ibm_runtime/sampler.py
qiskit_ibm_runtime/session.py
qiskit_ibm_runtime/utils/utils.py
test/integration/test_estimator.py
test/integration/test_sampler.py
test/integration/test_session.py
test/unit/test_estimator.py
test/unit/test_ibm_primitives.py
test/unit/test_sampler.py

Calculate circuit id by serializing and hashing the circuit key. Pass `circuits_map` and `circuit_ids` instead of `circuit_indices`.
Fixes #

Update for flexible session with data caching

---

qiskit_ibm_runtime/estimator.py
qiskit_ibm_runtime/sampler.py
test/integration/test_estimator.py
test/integration/test_sampler.py
test/unit/test_estimator.py
test/unit/test_ibm_primitives.py
test/unit/test_sampler.py

Data caching is causing significant performance issue right now. This PR disables it until that's fix. 
Fixes #

Disable data caching temporarily

---

.github/workflows/ci.yml
releasenotes/notes/python-3.10-support-904322454d2d504e.yaml
setup.py
tox.ini

Add Python 3.10 support

---

test/integration/test_estimator.py
test/integration/test_options.py
test/integration/test_session.py

Default resilience level is now, causing some of the tests to fail.
Fixes #

Fix integration test

---

docs/_templates/versions.html

Added back code that was deleted in https://github.com/Qiskit/qiskit-ibm-runtime/pull/599
Fixes https://github.com/Qiskit/qiskit-ibm-runtime/issues/608 and https://github.com/Qiskit/qiskit-ibm-runtime/issues/611
Tested locally,

Add back language switcher and fix formatting issues

---

.github/workflows/docs.yml

Docs deploy is failing, there is an isssue with the `setup-python` version 
https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/3716377844
Fixes #

Update setup-python version

---

docs/cloud/plans.rst
docs/cloud/quickstart-steps-org.rst
docs/cloud/quickstart.rst

Update the documentation to reflect that the Standard access plan now includes simulators
Fixes #

Standard plan includes simulators

---

docs/how_to/run_session.rst

Fix broken link in session docs 

---

docs/cloud/cost.rst

The UI is being updated so people can set a cost limit for their instance
Fixes #

Update text for Cloud UI changes

---

docs/conf.py
tools/deploy_translatable_strings.sh

The build for pushing translatable po files were broken (https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/4108453132/jobs/7089163037). This PR intends to fix that issue
Fixes #

Fix translatable files build failure

---

docs/tutorials/user-transpiled-circuits.ipynb

Update user-transpilied-circuits tutorial wording

---

docs/tutorials/how-to-getting-started-with-estimator.ipynb
docs/tutorials/how-to-getting-started-with-sampler.ipynb

Fix "Rumtime" typo in Estimator tutorial

---

test/decorators.py
test/integration/test_backend.py
test/integration/test_job.py
test/integration/test_retrieve_job.py

Skipping all failing test on staging due to fake backend incompatibilities, or custom programs that don't exist
example: https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/4229174184/jobs/7345309669
Fixes #

Skip unsupported tests on staging

---

qiskit_ibm_runtime/utils/utils.py
test/unit/mock/fake_runtime_client.py

Cleaning small issues in the code.
Removed redundant assignments to count in `fake_runtime_client.py`.
Changed `notifyAll` to `notify_all` to avoid warning in `lint`.

Code cleaning of small issues

---

test/integration/test_job.py

Test case was failing because the entire error message is no longer returned 
Fixes #

Fix `test_run_program_failed` integration test

---

qiskit_ibm_runtime/qiskit_runtime_service.py

Improved documentation for `filters` in `backends()` method
Added more examples for usage of the `filters` and `kwargs` parameters in `backends()`.
Removed example that was not working.
The same fix will be made in the documentation of `qiskit-ibm-providers`
Fixes #689.

Improved documentation for 'filters' in 'backends()' method

---

qiskit_ibm_runtime/qpy/binary_io/circuits.py

Credit to https://github.com/Qiskit/qiskit-terra/pull/9525 @jakelishman 
Fixes #

Add terra 0.23.2 QPY updates

---

qiskit_ibm_runtime/utils/backend_converter.py
releasenotes/notes/custom-gate-transpile-bug-61b64e4937269f28.yaml

Add ECR and CZ gate mapping

---

qiskit_ibm_runtime/qiskit_runtime_service.py

Improve error message when retrieving cloud backends

---

qiskit_ibm_runtime/qiskit_runtime_service.py

Update backend instance docstring

---

docs/how_to/run_session.rst

@jyu00 requested stronger wording for this note.
✅ I have added the tests to cover my changes.
✅ I have updated the documentation accordingly.
✅ I have read the CONTRIBUTING document.
-->
Fixes #

update Sessions note to be stronger

---

test/unit/test_session.py

Add test case for passing a backend in options

---

docs/how_to/retrieve_results.rst
docs/how_to/run_session.rst
docs/index.rst

Split sessions topic into two

---

qiskit_ibm_runtime/options/environment_options.py
qiskit_ibm_runtime/options/options.py
qiskit_ibm_runtime/options/resilience_options.py
qiskit_ibm_runtime/options/transpilation_options.py
releasenotes/notes/additional-options-validation-999888470cbd206e.yaml
test/unit/test_ibm_primitives.py

Added validation methods for `environment` and `transpilaton` options.
Fixes #

More validation of options

---

docs/index.rst

Simpler and more accurate descriptions of the Sampler and Estimator.

Clarify Estimator and Sampler descriptions in docs index.

---

docs/migrate/migrate-guide.rst
docs/primitives.rst

Closes #839.  I built this locally and verified that the links are fixed.

Fix broken links on Primitives page

---

requirements-dev.txt
requirements.txt
setup.py
test/unit/test_data_serialization.py

Remove scikit-quant & unpin numpy

---

test/integration/test_results.py

Use qasm simulator in `test_callback_error`

---

.github/workflows/ci.yml
.github/workflows/integration-tests.yml
.pylintrc
qiskit_ibm_runtime/api/rest/root.py
qiskit_ibm_runtime/api/rest/runtime_session.py
qiskit_ibm_runtime/ibm_qubit_properties.py
qiskit_ibm_runtime/options/execution_options.py
qiskit_ibm_runtime/qpy/binary_io/schedules.py
qiskit_ibm_runtime/qpy/binary_io/value.py
qiskit_ibm_runtime/runtime_job.py
qiskit_ibm_runtime/utils/utils.py
releasenotes/notes/python-3.11-support-edb6c144032bf483.yaml
requirements-dev.txt
setup.py
test/decorators.py
test/integration/test_account.py
test/integration/test_options.py
tox.ini

Support python 3.11

---

test/integration/test_backend.py

Test `test_backends_no_config` only in the quantum channel

---

docs/tutorials/Error-Suppression-and-Error-Mitigation.ipynb

Fix tutorial typo

---

docs/how_to/run_session.rst

Broken link

---

test/integration/test_retrieve_job.py

Job tags test needed to be updated because of the inability to delete jobs the past few months 
Fixes #

Update retrieve job integration tests

---

docs/tutorials/qaoa_with_primitives.ipynb

@HwajungKang - Should the session be manually closed?  I know it doesn't have to be, but we've been closing it in other places so it doesn't have to wait the whole 5 min of idle time before timing out.

Minor QAOA tutorial edits

---

docs/tutorials/grover_with_sampler.ipynb

@nonhermitian , should the session be manually closed?  I know it'll close on its own, but in other places we're closing it so it doesn't waste time waiting to time out.

Minor edits of Grover tutorial

---

releasenotes/notes/0.11/deprecate-bss-seconds-565fc01de679084f.yaml

Prepare release 0.11.1

---

test/integration/test_backend.py

cloud channel account only has simulators, which don't have properties, so this test should be on the quantum channel only 
Fixes #

Update deepcopy backend test

---

docs/index.rst

Document the version number

---

requirements.txt
setup.py

Update minimum qiskit-ibm-provider version

---

test/integration/test_job.py
test/integration/test_results.py

Minor updates to integration tests

---

docs/how_to/retrieve_results.rst

Fix a typo (ltar -> later).

---

README.md
docs/tutorials/chsh_with_estimator.ipynb

Minor docs fixes

---

docs/tutorials/Error-Suppression-and-Error-Mitigation.ipynb

remove email addresses

---

docs/tutorials/Error-Suppression-and-Error-Mitigation.ipynb

Remove names from tutorials
Fixes #

Remove names

---

docs/index.rst

Forgot to do this in the release prep, i'll cherry-pick into the stable branch and redeploy 
Fixes #

Update docs frontpage version

---

docs/faqs/max_execution_time.rst

Update docs on `max_execution_time` to indicate it's now quantum time, and there is also a timeout value dynamically calculated by the system.
Fixes #

Update docs on max_execution_time

---

qiskit_ibm_runtime/ibm_backend.py
qiskit_ibm_runtime/options/__init__.py
qiskit_ibm_runtime/qiskit_runtime_service.py

Fix spelling issues found via spellchecker

---

test/integration/test_job.py
test/integration/test_options.py

Need to use a different circuit to test `resilience_level` 3
Fixes #

Fix failing options test

---

requirements.txt
setup.py

Update qiskit & provider versions

---

qiskit_ibm_runtime/runtime_job.py
releasenotes/notes/error-message-case-31b4b2b7a5a2f624.yaml

Don't convert error messages to uppercase

---

qiskit_ibm_runtime/ibm_backend.py
qiskit_ibm_runtime/program/program_backend.py

Removed remaining code related to Schedules, meas_lo_freq, qubit_lo_freq, schedule_los.
See https://github.com/Qiskit/qiskit-ibm-provider/pull/724.

Removed remaining code related to Schedules

---

qiskit_ibm_runtime/api/clients/runtime.py
qiskit_ibm_runtime/api/rest/cloud_backend.py
qiskit_ibm_runtime/ibm_backend.py
qiskit_ibm_runtime/utils/backend_converter.py
releasenotes/notes/backend-properties-datetime-0fe6a364c0a291d2.yaml
test/integration/test_backend.py

Enable datetime parameter for backend properties

---

qiskit_ibm_runtime/base_primitive.py
qiskit_ibm_runtime/options/options.py
qiskit_ibm_runtime/options/resilience_options.py
releasenotes/notes/default-resilience-options-7929458af000314f.yaml
test/integration/test_options.py

Options that have the value `None` should be removed and not sent to the server. 
Fixes #1048

Update default resilience options

---

test/integration/test_options.py

forgot to fix this in #1062 
Fixes #

Fix resilience options test

---

qiskit_ibm_runtime/exceptions.py

RuntimeJobTimeoutError should inherit from JobTimeoutError

---

test/integration/test_job.py

Skipping `test_job_logs` until more logging is added on the primitives side. 
cc: @cpkurotori 
Fixes #

Skip test_job_logs

---

qiskit_ibm_runtime/session.py

https://github.com/Qiskit/qiskit-ibm-runtime/issues/1064#issuecomment-1724289586
Fixes #

Update session max_time docstring

---

README.md

- Remove the line that says IQP is the default (since it's not)
- Use "IQP channel" instead of "IQP services"
- Fix IQP account page link
- Added code on using `instances()`
- My IDE also trimmed trailing whitespaces 
Fixes #

Fix IQP link in README

---

qiskit_ibm_runtime/session.py
releasenotes/notes/from_id-23fc85f3fbf01e0b.yaml
test/integration/test_session.py
test/unit/test_session.py

New method to create a new Session object with a given id

---

test/integration/test_session.py

removing instance parameter, so test works on cloud channel 
Fixes #

Fix test_session_from_id

---

docs/faqs/max_execution_time.rst

Add IBM Cloud channel

---

test/integration/test_estimator.py
test/integration/test_sampler.py

These tests only worked because of a bug on the primitives side that was recently fixed. We shouldn't have been testing error message this way in the first place so removing the tests for now. 
Fixes #

Remove error message test

---

.github/workflows/deploy.yml

Migrate to PyPI Trusted Publishers 

---

test/ibm_test_case.py
test/unit/test_data_serialization.py

Fail unit tests on deprecation warning

---

requirements.txt
setup.py

Update minimum qiskit-ibm-provider version to `0.7.2` to include latest qpy updates
Fixes #

Update qiskit-ibm-provider version 0.7.2

---

test/integration/test_backend_serialization.py

Testing is failing on cloud staging because of invalid backend config 
Fixes #

Update backend serialization test

---

test/integration/test_ibm_job_attributes.py

Fix job_tags test & remove irrelevant skipped tests

---

test/integration/test_backend.py
test/integration/test_ibm_job.py
test/integration/test_ibm_qasm_simulator.py

Some of the tests copied over from the backend.run() update need to be refactored in this repo 
Fixes #

Update integration tests after backend.run() update

---

test/integration/test_backend_serialization.py

Add "coords" to good_keys in `test_backend_configuration`

---

qiskit_ibm_runtime/qiskit_runtime_service.py

Patch warning wording

---

qiskit_ibm_runtime/ibm_backend.py
test/integration/test_session.py

Added method `IBMBackend.close_session()`.
Same as in https://github.com/Qiskit/qiskit-ibm-provider/pull/762.

Add method close_session for IBMBackend

---

test/integration/test_session.py

Removing this test, as it sometimes runs jobs on real backend
Should have been removed in https://github.com/Qiskit/qiskit-ibm-runtime/pull/1267
Fixes #

Remove test_session_no_backend

---

docs/tutorials/grover_with_sampler.ipynb

Update grover tutorial equation

---

qiskit_ibm_runtime/qiskit_runtime_service.py
releasenotes/notes/dynamic-circuits-filter-59f771a9b43c00cd.yaml

Cherry picked from https://github.com/Qiskit/qiskit-ibm-provider/pull/434
Fixes #1290

Add dynamic circuits backend filter

---

qiskit_ibm_runtime/session.py

Update session_id docstring

---

requirements.txt
setup.py

Update provider and qiskit versions

---

test/integration/test_auth_client.py

Update invalid token test

---

MANIFEST.in

Backport of fake backend fix to `stable/0.17`.
Fixes #1371.

[Backport of #1319] Add fake backends to manifest 

---

qiskit_ibm_runtime/base_primitive.py
qiskit_ibm_runtime/utils/backend_decoder.py
qiskit_ibm_runtime/utils/utils.py
releasenotes/notes/deprecate-abstract-circuits-d9bdc94b2be7ea21.yaml

Add deprecation warning for abstract circuits

---

docs/tutorials/Error-Suppression-and-Error-Mitigation.ipynb
docs/tutorials/how-to-getting-started-with-estimator.ipynb
docs/tutorials/how-to-getting-started-with-sampler.ipynb
qiskit_ibm_runtime/fake_provider/__init__.py

Docs build is failing after the Qiskit 1.0 release yesterday 
Fixes #

Fix docs build with Qiskit 1.0 

---

setup.py

Update qiskit version in `setup.py` according to https://github.com/Qiskit/qiskit-ibm-runtime/pull/1423#issuecomment-1961685007

Upgrade to qiskit>=1.0.0 in setup.py

---

releasenotes/notes/0.20/session-modes-5c22b68620f8d690.yaml

Updating sessions mode release note per: https://github.com/Qiskit/qiskit-ibm-runtime/issues/1428#issuecomment-1966872701
Fixes #

Update sessions mode release note

---

qiskit_ibm_runtime/utils/json.py

Update en/decoding of `DataBin` to match server
Fixes #

Update DataBin encoding to match server

---

tox.ini

See https://github.com/Qiskit/qiskit-ibm-provider/pull/825 for context.

Fix bad tox.ini passenv setting

---

tox.ini

See https://github.com/Qiskit/qiskit-ibm-provider/pull/825 for context.

Fix bad tox.ini passenv setting (Cherry-pick of #1445)

---

qiskit_ibm_runtime/qiskit_runtime_service.py

Update backend() type hint to BackendV2

---

qiskit_ibm_runtime/runtime_job.py
qiskit_ibm_runtime/utils/estimator_result_decoder.py

Update EstimatorV2 result decoder.

Update EstimatorV2 result decoder

---

qiskit_ibm_runtime/__init__.py
releasenotes/notes/v2-primitives-ada671f4df7caa39.yaml
tox.ini

Remove experimental warning and enable sphinx -W
Fixes #

Remove experimental warning and enable -W

---

docs/tutorials/how-to-getting-started-with-estimator.ipynb
docs/tutorials/how-to-getting-started-with-sampler.ipynb
qiskit_ibm_runtime/estimator.py
qiskit_ibm_runtime/provider_session.py
qiskit_ibm_runtime/sampler.py
qiskit_ibm_runtime/session.py

Remove mentions of session caching

---

test/integration/test_estimator_v2.py
test/integration/test_sampler_v2.py

Fix V2 primitive integration tests

---

qiskit_ibm_runtime/__init__.py

Missed this in #1493 🤦‍♂️
Fixes #

Patch init docstring

---

qiskit_ibm_runtime/estimator.py
qiskit_ibm_runtime/sampler.py

This PR adds a version variable to the V1 classes.

Add missing versions to V1 classes

---

qiskit_ibm_runtime/utils/json.py

Server side has been updated to use Qiskit 1.0 
Fixes #1410

Bump qpy version in encoder

---

release-notes/unreleased/1527.bug.rst

Patch release note 0.21.2

---

release-notes/0.21.2.rst
release-notes/unreleased/1527.bug.rst

Cherry pick 0.21.2 release notes back to main

---

requirements.txt

Backport of #1500.
I believe this change is important enough to backport to the current stable branch, since it can lead to an `ImportError` otherwise.

Add pydantic to requirements (backport of #1500 to stable/0.21)

---

release-notes/0.22.0.rst
release-notes/unreleased/1409.upgrade.rst
release-notes/unreleased/1495.feat.rst
release-notes/unreleased/1541.bug.rst

Prepare 0.22.0 release

---

release-notes/0.1.0.rst
release-notes/0.1.0rc1.rst
release-notes/0.1.0rc2.rst
release-notes/0.11.0.rst
release-notes/0.11.1.rst
release-notes/0.11.2.rst
release-notes/0.11.3.rst
release-notes/0.12.0.rst
release-notes/0.12.1.rst
release-notes/0.13.0.rst
release-notes/0.14.0.rst
release-notes/0.15.0.rst
release-notes/0.15.1.rst
release-notes/0.17.0.rst
release-notes/0.18.0.rst
release-notes/0.2.0.rst
release-notes/0.20.0.rst
release-notes/0.4.0.rst
release-notes/0.5.0.rst
release-notes/0.6.0.rst
release-notes/0.7.0.rst
release-notes/0.7.0rc1.rst
release-notes/0.7.0rc2.rst
release-notes/0.8.0.rst
release-notes/0.9.0.rst
release-notes/0.9.1.rst
release-notes/0.9.2.rst
release-notes/0.9.3.rst
release-notes/0.9.4.rst

This PR is a cherry-pick of #1553 into `stable/0.22`

Cherrypick #1553 into `stable/0.22`

---

test/qctrl/test_qctrl.py

Updating the test thresholds, the tests should not fail because the result accuracy is not within our control. 
Fixes #

Update Q-CTRL test thresholds

---

qiskit_ibm_runtime/utils/backend_converter.py

Add delay instruction without pulse defaults

---

test/integration/test_estimator.py
test/unit/test_data_serialization.py
test/unit/test_estimator.py
test/unit/test_sampler.py
test/utils.py

Update v2 primitive unit tests

---

test/integration/test_backend_serialization.py
test/integration/test_retrieve_job.py

Fix test_backend_properties

---

qiskit_ibm_runtime/base_runtime_job.py
qiskit_ibm_runtime/runtime_job.py
qiskit_ibm_runtime/runtime_job_v2.py
release-notes/unreleased/1547.bug.rst

Use status() for related methods

---

qiskit_ibm_runtime/estimator.py
qiskit_ibm_runtime/session.py
release-notes/unreleased/1567.feat.rst

Add elapsed_time to session details

---

qiskit_ibm_runtime/api/session.py
release-notes/unreleased/1508.bug.rst

Fixes a bug added in https://github.com/Qiskit/qiskit-ibm-runtime/commit/36d7c15cc6702174150c7ce04d5054c777c6c502 that caused custom headers to not be sent in the /jobs api request 
Fixes #1508

Custom header not being sent

---

qiskit_ibm_runtime/utils/json.py
test/unit/test_data_serialization.py

Decode empty Databin's

---

release-notes/0.23.0.rst
release-notes/unreleased/1476.bug.rst
release-notes/unreleased/1490.feat.rst
release-notes/unreleased/1508.bug.rst
release-notes/unreleased/1521.bug.rst
release-notes/unreleased/1531.feat.rst
release-notes/unreleased/1547.bug.rst
release-notes/unreleased/1550.feat.rst
release-notes/unreleased/1557.feat.rst
release-notes/unreleased/1561.deprecation.rst
release-notes/unreleased/1567.feat.rst

Prepare release 0.23.0

---

release-notes/0.23.0.rst

https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/release-notes
Updating the most recent release notes to have appropriate hyperlinks and highlighted words.
Things to note: 
- Double back ticks `` highlight words, single back ticks don't seem to have any effect.  
- We should hyper link class names and methods when possible `:class: .class_name`, or `text <url>__`.

Prettify release notes

---

.github/workflows/ci.yml

Workaround for https://github.com/actions/setup-python/issues/696
Fixes #

Fix macos-latest python 3.8/9 github actions compatibility

---

test/qctrl/test_qctrl.py

Use batch in q-ctrl tests

---

qiskit_ibm_runtime/session.py

Remove local session warning

---

test/unit/test_data_serialization.py

Fixes #1651.
Note that the [change to qiskit](https://github.com/Qiskit/qiskit/pull/12219) in question, at the time of this writing, is not yet on qiskit main, it's still in the merge queue.

Switch DataBin instantiation to use keyword arguments

---

test/integration/test_backend.py

Fix qubit properties test

---

qiskit_ibm_runtime/ibm_backend.py
test/unit/transpiler/passes/scheduling/test_scheduler.py

Skipping the unit tests for now so other PRs are not blocked 
Fixes #1641

Add translation plugin

---

release-notes/0.14.0.rst

This is the final planned URL.

Update Serverless URL to final destination

---

test/ibm_test_case.py
test/integration/test_ibm_job.py
test/integration/test_retrieve_job.py

Add samplerv2 option to ibm_test_case & remove lazy loading params test

---

test/integration/test_ibm_job.py
test/integration/test_ibm_job_attributes.py

Missed 2 tests that needed to be updated 
Fixes #

Follow up to #1571

---

qiskit_ibm_runtime/accounts/management.py

URL is not required when initializing account from env variables 

---

qiskit_ibm_runtime/utils/json.py
test/unit/test_data_serialization.py

Decode numpy array with ints

---

qiskit_ibm_runtime/session.py

Accommodate new session status

---

qiskit_ibm_runtime/qiskit_runtime_service.py

Add private_endpoint to constructor

---

qiskit_ibm_runtime/options/estimator_options.py
release-notes/unreleased/1728.feat.rst

Document that PEA is an available experimental option.
Fixes #

Document PEA as an experimental option

---

qiskit_ibm_runtime/options/estimator_options.py

Update PEA docstring to address [this comment](https://github.com/Qiskit/qiskit-ibm-runtime/pull/1728#discussion_r1626785089). 
Fixes #

Update PEA docstring

---

README.md

Add `Authors and Citation` section to README.
Fixes #

Update README to add citation section

---

test/integration/test_backend.py

Caching backends was updated/removed in #1732, causing these integration tests to fail 
Fixes #

Fix backend tests after #1732

---

qiskit_ibm_runtime/base_primitive.py
qiskit_ibm_runtime/estimator.py
qiskit_ibm_runtime/sampler.py

https://github.com/Qiskit/qiskit-ibm-runtime/pull/1584#issuecomment-2161325933
Fixes #

Update deprecation msg with correct version

---

.github/workflows/ci.yml

Excluding the unit tests that use python 3.8 and 3.9 on macos. There was a brew update that doesn't seem to be supported by coveralls on the `macos-13` build. 
Fixes #

Fix macos-13 gh actions build

---

release-notes/0.24.1.rst
release-notes/unreleased/1755.bug.rst

Cherry picking patch release notes from `stable/0.24` back into main 
Fixes #

Cherry pick 0.24.1 patch release notes

---

test/integration/test_ibm_job_attributes.py

Forgot this in #1771, this test should only test on the ibm_quantum channel, not cloud 
Fixes #

Skip job instance test on cloud

---

qiskit_ibm_runtime/runtime_job.py
qiskit_ibm_runtime/runtime_job_v2.py
release-notes/unreleased/1776.deprecation.rst

We'll need a follow up PR after the deprecation period to remove all of the interim results streaming code. 
Fixes #1774

Deprecate interim results

---

release-notes/0.25.0.rst
release-notes/unreleased/1740.upgrade.rst
release-notes/unreleased/1748.deprecation.rst
release-notes/unreleased/1764.feat.rst
release-notes/unreleased/1771.feat.rst
release-notes/unreleased/1773.feat.rst
release-notes/unreleased/1776.deprecation.rst

Prepare release 0.25.0

---

.github/ISSUE_TEMPLATE/config.yml

Old names in the issue template

---

docs/conf.py

Added intersphinx to allow the linking of Runtime docs to Qiskit docs
Fixes #1611

Added Intersphinx to docs

---

test/integration/test_retrieve_job.py

Remove job params test

---

test/integration/test_fake_backends.py

Test only runs on IQP production since that's the only instance we have access to a real backend 
Fixes #

Update test_refresh_method test again

---

qiskit_ibm_runtime/batch.py
qiskit_ibm_runtime/estimator.py
qiskit_ibm_runtime/sampler.py
qiskit_ibm_runtime/session.py
release-notes/unreleased/1804.deprecation.rst

Deprecate passing backend as a string

---

qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py
qiskit_ibm_runtime/transpiler/passes/scheduling/scheduler.py
test/unit/test_local_mode.py

DD updates cherry picked from qiskit - https://github.com/Qiskit/qiskit/pull/12459/files#diff-582f3a24b02b86bd19503162886e2b4410b0d6552273462026188a69eec4115b
Fixes #1770

Update unit tests for Qiskit 1.2

---

test/unit/test_estimator.py
test/unit/test_sampler.py
test/utils.py

`test_run_program_inputs` in `test_sampler.py` wasn't actually testing anything because the length of the pubs was less than 2. 
Fixes #1721

Update transpile_pubs for unit tests

---

qiskit_ibm_runtime/base_primitive.py
release-notes/unreleased/1816.deprecation.rst
test/integration/test_session.py

Add deprecation msg for session precendence

---

qiskit_ibm_runtime/batch.py
qiskit_ibm_runtime/session.py
release-notes/unreleased/1826.deprecation.rst

https://github.com/Qiskit/qiskit-ibm-runtime/pull/1804#issuecomment-2257067199
Fixes #

Deprecate `service` in session & batch

---

qiskit_ibm_runtime/options/twirling_options.py
qiskit_ibm_runtime/qiskit_runtime_service.py

The changes are related to fractional gates.

Small doc changes

---

qiskit_ibm_runtime/base_primitive.py
test/integration/test_noise_learner.py

#1805 accidentally overwrote the deprecation warnings in #1816, adding them back here. 
Fixes #

Fix failing integration tests 

---

release-notes/0.26.0.rst
release-notes/unreleased/1765.feat.rst
release-notes/unreleased/1780.feat.rst
release-notes/unreleased/1783.feat.rst
release-notes/unreleased/1784.bug.rst
release-notes/unreleased/1791.bug.rst
release-notes/unreleased/1792.bug.rst
release-notes/unreleased/1793.feat.rst
release-notes/unreleased/1794.feat.rst
release-notes/unreleased/1800.bug.rst
release-notes/unreleased/1804.deprecation.rst
release-notes/unreleased/1805.feat.rst
release-notes/unreleased/1816.deprecation.rst
release-notes/unreleased/1826.deprecation.rst

Prepare release 0.26.0

---

release-notes/0.26.0.rst

I'll cherry pick this into `stable/0.26`
Fixes #

Add warning about backend module change

---

README.md
qiskit_ibm_runtime/base_primitive.py
qiskit_ibm_runtime/batch.py
qiskit_ibm_runtime/estimator.py
qiskit_ibm_runtime/ibm_backend.py
qiskit_ibm_runtime/noise_learner/noise_learner.py
qiskit_ibm_runtime/options/estimator_options.py
qiskit_ibm_runtime/options/options.py
qiskit_ibm_runtime/provider_session.py
qiskit_ibm_runtime/sampler.py
qiskit_ibm_runtime/session.py
qiskit_ibm_runtime/transpiler/passes/__init__.py
qiskit_ibm_runtime/utils/validations.py
release-notes/0.20.0.rst
release-notes/0.21.0.rst
release-notes/0.23.0.rst
release-notes/0.24.0.rst

Part of https://github.com/Qiskit/documentation/issues/1461. Even though these pages have redirects, it's better to go straight to the page we want.

Update docs links for new structures

---

release-notes/0.27.0.rst
release-notes/unreleased/1838.bug.rst
release-notes/unreleased/1844.feat.rst

Prepare release 0.27.0

---

release-notes/0.27.1.rst

Cherry pick 0.27.1 release notes into main

---

qiskit_ibm_runtime/options/zne_options.py
test/unit/test_estimator_options.py

This PR exposes the PEA mitigation method in the ZNE options. It also exposes another helpful option to do with specifying the points at which extrapolation methods are evaluated.
Test evidence is incoming.

Make PEA option public

---

qiskit_ibm_runtime/estimator.py
test/unit/test_estimator.py

Validate precision in `estimator.run()`

---

qiskit_ibm_runtime/options/estimator_options.py

Remove PEA as an experimental option since it's a real option now. 
Fixes #

Remove PEA as an experimental option

---

README.md
qiskit_ibm_runtime/options/__init__.py
qiskit_ibm_runtime/options/environment_options.py

Some additional doc cleanup for V1 removal. 
Fixes #

Doc cleanup for V1

---

qiskit_ibm_runtime/session.py
release-notes/unreleased/1868.other.rst
test/integration/test_session.py

In preparation for `0.28.0` release
Fixes #

Remove session id "service" param deprecation

---

release-notes/0.28.0.rst
release-notes/unreleased/1857.other.rst
release-notes/unreleased/1858.feat.rst
release-notes/unreleased/1868.other.rst

Prepare release 0.28.0

---

qiskit_ibm_runtime/execution_span.py
qiskit_ibm_runtime/utils/json.py
qiskit_ibm_runtime/utils/validations.py
release-notes/unreleased/1833.feat.rst
test/unit/test_data_serialization.py
test/unit/test_execution_span.py

The new classes `ExecutionSpan` and `ExecutionSpanCollection` will be populated with timing information of sampler jobs.
Closes #1832.

Execution span classes

---

release-notes/0.29.0.rst
release-notes/unreleased/1833.feat.rst
release-notes/unreleased/1888.feat.rst
release-notes/unreleased/1890.bug.rst
release-notes/unreleased/1891.bug.rst
release-notes/unreleased/1892.deprecation.rst
release-notes/unreleased/1896.bug.rst
release-notes/unreleased/1902.feat.rst

Prepare release 0.29.0

---

.github/workflows/ci.yml
test/integration/test_noise_learner.py

Fixing broken integration test

Fixing broken integration test

---

test/integration/test_ibm_job_attributes.py

Skip test_private_option on cloud channel

---

release-notes/0.29.1.rst
release-notes/unreleased/1908.feat.rst

Patch release, includes `NoiseLearnerResult` serialization bug fix 
Fixes #

Prepare release 0.29.1

---

release-notes/0.29.1.rst
release-notes/unreleased/1908.feat.rst

Cherry pick 0.29.1 release notes 

---

.github/workflows/ci.yml
.github/workflows/integration-tests-qiskit-main.yml
.github/workflows/integration-tests.yml
.github/workflows/unit-tests-terra-main.yml

Add `requirements-visual.txt` to CI so tests don't fail 
Fixes #

Add requirements-visual install to CI

---

test/integration/test_job.py
test/integration/test_retrieve_job.py

Missed these in #1907 
Fixes #

Update tests with program_id

---

qiskit_ibm_runtime/runtime_job.py
qiskit_ibm_runtime/runtime_job_v2.py

Add "deprecated" to streaming methods docstring

---

CONTRIBUTING.md
docs/apidocs/debug_tools.rst
docs/apidocs/index.rst
qiskit_ibm_runtime/debug_tools/__init__.py

Adds docs for `Neat` and related classes

Adding `debug_tools` to API docs

---

qiskit_ibm_runtime/options/zne_options.py

Fix minor typo

---

test/integration/test_backend.py
test/integration/test_ibm_job.py

Minor integration test updates

---

setup.py

Allow pip install `qiskit-ibm-runtime[visualization]`

---

test/integration/test_backend.py

Skip test_backend_deepcopy if simulator

---

release-notes/0.33.0.rst
release-notes/unreleased/1988.feat.rst
release-notes/unreleased/2011.feat.rst
release-notes/unreleased/2012.other.rst
release-notes/unreleased/2014.bug.rst

Prepare release 0.33.0

---

release-notes/0.33.1.rst

Cherry pick 0.33.1 release notes into main (#2029)

---

release-notes/0.33.2.rst

Cherry pick 0.33.2 release notes

---

qiskit_ibm_runtime/runtime_job.py

Update job status deprecation msg

---

qiskit_ibm_runtime/utils/noise_learner_result.py
qiskit_ibm_runtime/visualization/__init__.py

This PR adds swarm plotters to the docs

Adding swarm plotter to the docs

---

test/ibm_test_case.py

Update ibm_test_case to not use other `test_` backends

---

.github/workflows/ci.yml

Install visualization package in integration test CI

---

qiskit_ibm_runtime/__init__.py
qiskit_ibm_runtime/session.py

Update doc code examples

---

qiskit_ibm_runtime/fake_provider/__init__.py
qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py
qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py

We're trying to make sure that every image has alt text for accessibility.

Add alt text to images

---

qiskit_ibm_runtime/fake_provider/__init__.py
qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py
qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py

Brackets around alt text are not needed.

Remove brackets from alt text

---

CONTRIBUTING.md
README.md
qiskit_ibm_runtime/accounts/account.py
qiskit_ibm_runtime/constants.py
qiskit_ibm_runtime/qiskit_runtime_service.py
test/decorators.py
test/unit/test_account.py
test/unit/test_client_parameters.py

Updating urls from quantum-computing.ibm.com to quantum.ibm.com and from ibm.com/quantum-computing to ibm.com/quantum
Fixes #

Updating URL subdomain

---

qiskit_ibm_runtime/fake_provider/__init__.py
qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py
qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py

We're trying to make sure that every image has alt text for accessibility.

Add alt text to images (backport #2079)

---

qiskit_ibm_runtime/options/resilience_options.py

`layer_noise_model` should accept `None`

---

qiskit_ibm_runtime/base_primitive.py
qiskit_ibm_runtime/utils/__init__.py
qiskit_ibm_runtime/utils/utils.py
qiskit_ibm_runtime/utils/validations.py
test/unit/test_sampler.py

Remove parameter expression validation check for gen3-turbo
The gen3-turbo mode now supports this.

Remove parameter expression validation check for gen3-turbo

---

pyproject.toml

Add fallback version when installing package locally

---

docs/conf.py
pyproject.toml
release-notes/0.35.0.rst
release-notes/unreleased/1962.other.rst
release-notes/unreleased/2057.feat.rst
release-notes/unreleased/2093.other.rst
release-notes/unreleased/2097.upgrade.rst
release-notes/unreleased/2100.other.rst
release-notes/unreleased/2112.feat.rst

Prepare release 0.35.0

---

qiskit_ibm_runtime/noise_learner/noise_learner.py

Update NoiseLearner docs

---

docs/conf.py
pyproject.toml
release-notes/0.36.0.rst
release-notes/unreleased/2096.upgrade.rst
release-notes/unreleased/2124.other.rst

Prepare release 0.36.0

---

qiskit_ibm_runtime/utils/json.py
release-notes/unreleased/2144.bug.rst

As a dev dependency, `aer >= 0.16.1` is required so we don't actually need to check for the version 
Fixes #2142

Patch aer version bug

---

docs/conf.py
pyproject.toml
release-notes/0.36.1.rst
release-notes/unreleased/2144.bug.rst

Prepare release 0.36.1

---

qiskit_ibm_runtime/base_primitive.py
release-notes/unreleased/2152.feat.rst

Add warning if primitive initalized outside session

---

qiskit_ibm_runtime/fake_provider/__init__.py
qiskit_ibm_runtime/fake_provider/fake_backend.py

Update fake backend docs

---

test/integration/test_ibm_job_attributes.py
test/integration/test_retrieve_job.py

Add a one minute buffer 
Fixes #2160

Account for clock skew in creation_date tests

---

qiskit_ibm_runtime/ibm_backend.py
qiskit_ibm_runtime/utils/options.py

Update qiskit version check logic

---

CONTRIBUTING.md

Removing `$` to make commands copy and paste-able. 
Fixes #

Minor updates to `contributing.md`

---

docs/conf.py
pyproject.toml
release-notes/0.37.0.rst
release-notes/unreleased/2116.other.rst
release-notes/unreleased/2152.feat.rst
release-notes/unreleased/2153.bug.rst
release-notes/unreleased/2154.bug.rst
release-notes/unreleased/2156.bug.rst
release-notes/unreleased/2166.deprecation.rst

Prepare release 0.37.0

---

release-notes/0.28.0.rst
release-notes/0.30.0.rst
release-notes/0.31.0.rst
release-notes/0.32.0.rst
release-notes/0.33.0.rst
release-notes/0.34.0.rst
release-notes/0.35.0.rst
release-notes/0.36.0.rst

Breaking changes/removals should be in `Upgrade Notes` instead of `Other Notes`. 
Fixes #

Reorganize release note titles/headings

---

qiskit_ibm_runtime/fake_provider/fake_backend.py
qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py
qiskit_ibm_runtime/utils/backend_converter.py
release-notes/0.37.0.rst

Minor docs cleanup

---

docs/conf.py
pyproject.toml
release-notes/0.38.0.rst
release-notes/unreleased/2143.other.rst
release-notes/unreleased/2170.deprecation.rst
release-notes/unreleased/2184.bug.rst
release-notes/unreleased/2186.deprecation.rst
release-notes/unreleased/2202.feat.rst
release-notes/unreleased/2205.deprecation.rst

Prepare release 0.38.0

---

qiskit_ibm_runtime/qiskit_runtime_service.py
release-notes/0.38.0.rst

`local` is also a valid channel 
Fixes #

Update iqp warning text and 0.38 release note 

---

pyproject.toml

https://github.com/Qiskit/qiskit-ibm-runtime/pull/2049/files#r2049173942
Fixes #

Unpin upper pydantic version

---

qiskit_ibm_runtime/batch.py
qiskit_ibm_runtime/session.py
release-notes/unreleased/2222.bug.rst

`Backend` is not optional and there is already an error raised if no backend is passed in so we should be able to just remove the incorrect type hint. 
Fixes #

Fix session/batch type hint

---

docs/conf.py
pyproject.toml
release-notes/0.39.0.rst
release-notes/unreleased/2102.other.rst
release-notes/unreleased/2195.bug.rst
release-notes/unreleased/2222.bug.rst
release-notes/unreleased/2226.bug.rst
release-notes/unreleased/2231.feat.rst
release-notes/unreleased/2250.feat.rst
release-notes/unreleased/2250.other.rst

Prepare release 0.39.0

---

test/integration/test_account.py
test/integration/test_job.py
test/integration/test_retrieve_job.py

Fix failing new IQP tests

---

docs/conf.py
pyproject.toml
release-notes/0.40.1.rst
release-notes/unreleased/2269.bug.rst
release-notes/unreleased/todo.other.rst

Prepare patch release 0.40.1

---

docs/conf.py
pyproject.toml
release-notes/0.40.1.rst
release-notes/unreleased/2269.bug.rst
release-notes/unreleased/todo.other.rst

Since we did a patch release, the release notes were only pushed into the `stable/0.40` branch.
Fixes #

Cherry pick 0.40.1 release notes back into main 

---

qiskit_ibm_runtime/qiskit_runtime_service.py

Fix the missing space in the deprecation warning which breaks the hyperlink 
Fixes #

Fix missing space

---

.github/workflows/ci.yml
pyproject.toml
qiskit_ibm_runtime/__init__.py
release-notes/unreleased/2314.feat.rst
tox.ini

Update supported python versions

---

qiskit_ibm_runtime/api/clients/runtime.py
qiskit_ibm_runtime/api/rest/runtime.py
qiskit_ibm_runtime/qiskit_runtime_service.py
release-notes/unreleased/2329.feat.rst
test/integration/test_account.py

Also cleaned up the old usage() methods from IQP classic
Fixes #1829

Update usage method to include remaining usage

---

docs/conf.py
pyproject.toml
release-notes/0.41.1.rst
release-notes/unreleased/2359.bug.rst

Cherry pick the `stable/0.41` prepare release PR back into the main branch 
Fixes #

Cherry pick 0.41.1 release notes into main 

---

qiskit_ibm_runtime/session.py

Fix session doc code example

---

docs/apidocs/index.rst
docs/apidocs/models.rst
qiskit_ibm_runtime/models/__init__.py

Expose backend objects in docs
